### ISSUE TITLE
API Prompts not loadable in WebUI

### ISSUE THREAD

**Issue by fuami** [comfyanonymous/ComfyUI#1038]
Minor research shows that this is because the "workflow" metadata is not included in API generated images, only the "prompt" whereas WebUI generated images contain both.

I believe it would make sense for this to function; as the files were generated with ComfyUI so they should be completely compatible, just auto-arranged as the additional detail that "workflow" contains isn't present.

I considered trying my hand at it, but looking at ComfyApp.loadGraphData it looks like some level of refactoring will be needed in the creation of the new method so errors, patching, and other logic can be done in one place and not duplicated, and I don't think I'm versed enough in the project or the libraries it uses to make that happen.

**Comment by Satellile** [comment]
Issue #69 is somewhat relevant; Comfy said importing workflows from the api is a planned feature.

Hopefully Comfy or someone else is able to implement it, as I'd also love to see it. I have a simple tool using the API to save the queue to a disk to then run later, but since it retrieves the prompt from the API, the end results don't have workflow metadata embed, which is pretty inconvenient.

**Comment by TimPietrusky** [comment]
When this gets resolved, will `--disable-metadata` still get rid of the metadata, even when the image was generated by the API?

**Comment by Chaoses-Ib** [comment]
It's said in the plan in #1498. Seems already implemented in #1932.

**Comment by fuami** [comment]
Confirmed that its working!

**Comment by cpietsch** [comment]
this seems to be broken again
