### ISSUE TITLE
please update randomization to randomize BEFORE generation

### ISSUE THREAD

**Issue by mattymatty** [comfyanonymous/ComfyUI#1084]
The current behavior is randomized AFTER generation but that causes confusion when you are looking at a NEW random value, but not the value that was used for generation.

Please update with an option to randomize BEFORE generation so we are looking at the currently used value

**Comment by StephanGocht** [comment]
An easy workaround is to not set it to randomize but instead to increment the seed. If you want to reuse the previous seed it is quite easy to just decrement it manually and switch to fixed.

**Comment by Chalice** [comment]
I am actually working on a patch. It is working fine, randomizing the number before the sampling, but on a switch to fixed it re-runs the sampling. Working on it.

**Comment by howardelton** [comment]
Note that randomising the seed before generation would break the ability to use someone else's PNG file to load their workflow and generate the same image. If a great image is generated with a random seed, and shared with opther people, those people can open it and recreate the image exactly still, because the randomisation occurs afterwards.  If it were to randomise before, then this functionality would no longer work because seed changes before the first attempt to recreate it.

**Comment by ltdrdata** [comment]
> Note that randomising the seed before generation would break the ability to use someone else's PNG file to load their workflow and generate the same image. If a great image is generated with a random seed, and shared with other people, those people can open it and recreate the image exactly still, because the randomisation occurs afterwards.  If it were to randomise before, then this functionality would no longer work because seed changes before the first attempt to recreate it.

How about keeping the default as "control before," but providing a separate queue button that allows executing without changing the current seed? 

The "control after" feature has several non-intuitive aspects. Switching modes sometimes triggers behaviors that appear as bugs.

**Comment by mattymatty** [comment]
Automatic uses -1 for random. Why not just use that? If -1 then random seed. If some number like 458234832 then use that.

**Comment by jojorne** [comment]
> Automatic uses -1 for random. Why not just use that? If -1 then random seed. If some number like 458234832 then use that.

It would be great but currently, it's not a "seed" but a number generator. How all the other methods would look like? Fixed, Increment, etc. So it makes sense to have a listbox with ways to generate a new number. Having that box as increment or fixed and the value as -1 would not make sense. Of course the value would automatically change to reflect the method, e.g. in the case of fixed, it can't accept -1 otherwise it would generate a new number.

That said, it is possible to use -1 but each generator method would have to check and change the value. In this process you would lose your current "seed".

**Comment by jojorne** [comment]
> Note that randomising the seed before generation would break the ability to use someone else's PNG file to load their workflow and generate the same image. If a great image is generated with a random seed, and shared with other people, those people can open it and recreate the image exactly still, because the randomisation occurs afterwards. If it were to randomise before, then this functionality would no longer work because seed changes before the first attempt to recreate it.

If you set it to fixed, the value would not change, right? This would allow you to see their image.

Because it's just the first one, right? Since a second pass would be pointless anyway because it would be randomized.

**Comment by ricperry** [comment]
Not sure if this issue is closed, but I'd like to +1. When I need to tweak some settings, but like where a particular seed is going, I can't currently cancel the working process without losing the seed. I can only extract the seed if the file gets saved.

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/pull/2538

**Comment by indusguys** [comment]
at the very least we should be able to easily use last seed. having to load the image from the browser and then update everything you'd updated before you noticed the seed was random is so frustrating. Maybe you can do that but I've not found it yet.

**Comment by indusguys** [comment]
The 'oh, if you do that then this will break' responses, take the essence of what the person wants. In A1111 you can quickly recycle the last seed. That's the feature I think we all want.

**Comment by seeingrain** [comment]
vote for this issue, I'm also confused of this mechenism.

**Comment by ltdrdata** [comment]
> vote for this issue, I'm also confused of this mechenism.

![image](https://github.com/user-attachments/assets/f4e2d448-f4c8-489c-b4c9-a2d553ebaa4c)
