### ISSUE TITLE
[feature request] add pipeline to existing

### ISSUE THREAD

**Issue by John-WL** [comfyanonymous/ComfyUI#112]
I would love to save partial pipelines to combine them together later on. 

For instance, I could have a pipeline for denoising ("highres fix", for example), and a pipeline for prompting ("merging 4 different prompts together", for example). I would like to be able to import different parts of a pipeline like that to combine them. 

Like that, I could have a variety of building blocks which I could use to create a pipeline faster and more easily without having to repeat myself.

**Comment by AntonyDwornikBuW** [comment]
The code is not provided, but based on the explanation given, it seems like the person is describing their desire to create and save partial pipelines for denoising and prompting tasks, which can be imported and combined together later on to create a complete pipeline, in order to streamline their workflow and avoid repeating themselves.

**Comment by comfyanonymous** [comment]
You can now select a bunch of nodes -> right click the canvas -> save selected as template
