### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by Nufzy** [comfyanonymous/ComfyUI#1170]

**Comment by all500234765** [comment]
Just run the installation i've got from website and in logs it still requires it.
Would reopen the issue.

**Comment by all500234765** [comment]
Running '& "<Install Dir>\ComfyUI\.venv\Scripts\pip3.exe" install pyyaml' and then launching ComfyUI now shows "Install python packages" for me instead of endless loop of trying to setup ComfyUI, and then crashing due to unknown error.

Then tried running 
'& "<Install Dir>\ComfyUI\.venv\Scripts\pip3.exe" "install" "torch" "torchvision" "torchaudio" "--index-url" "https://download.pytorch.org/whl/cu128"' which seems to did the trick finally.

This is all due to multiple python installations, seems like something wasn't using correct one.
