### ISSUE TITLE
The zooming speed is too fast, I'm just gently scrolling the mouse.

### ISSUE THREAD

**Issue by tyzero** [comfyanonymous/ComfyUI#1192]
The zooming speed is too fast, I'm just gently scrolling the mouse.

window, chrome

**Comment by tyzero** [comment]
<img width="1193" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/6857741/52595e6e-c53f-4077-8386-7fb3591854c9">

**Comment by tyzero** [comment]
ok, I fixed it by turn off Logi mouse smooth scrolling option.

**Comment by tom-doerr** [comment]
Same issue on my Ubuntu ThinkPad with i3

**Comment by Iemand005** [comment]
I'm also having it zoom in way way too fast with both touch screen and trackpad, it's very annoying to zoom in on my laptop, I don't want to have to use an external mouse and give up portability just to be able to zoom. There should be a zoom speed slider, and if possible for touch screens the zoom should follow the touch gestures properly so that if I place one finger on one point and another on another point and move the two fingers around, those two points scale and move to stay under my fingers. This has been bothering me from the start, I'm surprised not that many others have noticed.
