### ISSUE TITLE
ComfyUI refusing to launch

### ISSUE THREAD

**Issue by LolTape** [comfyanonymous/ComfyUI#1211]
after installation it worked fine, but after closing the cmd and trying to launch it again.. it simply doesn't.. instead it runs it up until saying this:
-----------
x\Desktop\Comfy UI\ComfyUI_windows_portable>pause
Press any key to continue . . .

-----------
after I do it just shuts down.

I ran the nvidia starter

**Comment by LolTape** [comment]
![Skjermbilde 2023-08-14 025711](https://github.com/comfyanonymous/ComfyUI/assets/142187477/8ccae2a1-6c18-4336-b3c1-3b13e23adae4)

**Comment by LolTape** [comment]
![mzl nedtzwvh](https://github.com/comfyanonymous/ComfyUI/assets/142187477/6afb3d36-d411-4de6-9703-2ad7a1bc1847)

**Comment by ltdrdata** [comment]
btw... your manager version is too old. (current version is 0.22.4)
I recommend update ComfyUI-Manager, stronlgy.

**Comment by bollenta** [comment]
HI @LolTape i have the same issue, did you find a solution? Please somebody help :D

**Comment by serget2** [comment]
Updated straight from the github, guess what same issue, updating the old manager that worked to the new one, and updating ALL me this problem, updating the manager to the same version does not fix the issue, who would have thunk it?  Also did anyone say that the issue was installing missing nodes? HELL NAW, the issue at hand was that it pauses and stops when you press any key.
So if we please stick to this one issue first, because I can't install any nodes if comfyUI doesn't start first

**Comment by serget2** [comment]
Here is a solution that worked for me and maybe all of you should try that BEFORE you do anything else under comfyUI_windows_portable there is a folder called UPDATE, go figure, you go in to that folder and run the three Update....bat files and wait, then restart ComfyUI, no need for fingerpointing (Oh it's the manager, oh you need to delete all files oh BLAH BLAH BLAH BS). How about trying the bloody f*cking obvious first, you geniuses
