### ISSUE TITLE
Hypernetwork support

### ISSUE THREAD

**Issue by Wyrmspirit** [comfyanonymous/ComfyUI#123]
I saw in the closed issues someone requested this feature. Is this feature still in development? I want to stop using automatic1111 and switch over to ComfyUI but currently I can't do that because I use hypernetworks in my workflow.

**Comment by comfyanonymous** [comment]
Yes I plan on at least implementing support for the linear ones it has just not been that high on the priority list because not that many people seem to use them anymore.

**Comment by Wyrmspirit** [comment]
Thank you for the swift response. I understand, that's fair. I'll see if I can figure out a workaround in the meantime, I really like your UI.

**Comment by Miyuutsu** [comment]
I wanted to go ahead and add my voice into this as well. I use hypernetworks quite a lot and it's basically the last huge feature missing from making me a nearly 100% ComfyUI user since a bulk majority of features I need have been implemented or otherwise are implemented by custom nodes. Other than for hypernetworks I've basically completely replaced a1111 WebUI with ComfyUI and individual applications that perform WebUI plugin tasks better. Keep up the great work!

**Comment by comfyanonymous** [comment]
I have added support for linear hypernetworks, put them in the models/hypernetworks folder and use the new HypernetworkLoader node in _for_testing to load them.

Check your console, if it prints that your hypernetwork isn't supported let me know and I might write the code to support it.
