### ISSUE TITLE
[FEATURE] Adding TABS in the bottom of the UI (similar to EXCEL tabs) in order to be able to switch between multiple workflows

### ISSUE THREAD

**Issue by StableInfo** [comfyanonymous/ComfyUI#1239]
Same as EXCEL tabs, where you can select from one page to another one, I believe ComfyUI heavily needs one, it is especially good if you dont want to lose a workflow from your sight and be able to switch between workflows, it is useful for beginners when testing new workflows, comparing, looking out for differences and new nodes. 
It is generally useful for people who alternate between multiple workflows.

Can you implement it please? 
Thanks

**Comment by pennyvc** [comment]
This would be super cool, you could add them to the same queue and it shouldn't be incompatible

**Comment by fuami** [comment]
Pretty sure this is basically the same as #1173

**Comment by StableInfo** [comment]
Indeed, it shows how much needed it is indeed needed! Hopefully it will make it.
btw, does the repo master update comfy often?

**Comment by ltdrdata** [comment]
There are a few tricks for this.

You can use `--listen 0.0.0.0` and access it in the form of `127.0.0.1:8188`, `127.0.0.2:8188`, and so on.

The workflow itself will likely be separated. However, since the execution cache is shared, there's a limitation where running the workflow in one tab will reset the cache in other tabs. This is a non-negotiable aspect due to memory constraints, as avoiding simultaneous retention is necessary.

Alternatively, you can register them in the hosts file like this and access them as `comfy1:8188`, `comfy2:8188`, and so on.
```
127.0.0.1 comfy1 
127.0.0.1 comfy2
127.0.0.1 comfy3
```

In my case, I use the latter method.

**Comment by Lex-DRL** [comment]
@ltdrdata Thanks for the workaround suggestion.

... but still, it's just what it is: a workaround. And quite a hacky one, specially for "non-technical" users who struggle even with cloning a github repo.
We could use it your approach for now, but I believe the issue is still relevant. As much as before.

**Comment by Lex-DRL** [comment]
seems already implemented

**Comment by ltdrdata** [comment]
The structure of ComfyUI has changed, so the previously suggested method is no longer usable. You must use the tab provided by ComfyUI itself.
