### ISSUE TITLE
RuntimeError: Tensor.__contains__ only supports Tensor or scalar, but you passed in a <class 'str'>.

### ISSUE THREAD

**Issue by tzekeong** [comfyanonymous/ComfyUI#1333]
Hi Comfy UI,

I got the following exception after update to the latest code. Any help?

!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI\nodes.py", line 1207, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "D:\ComfyUI\nodes.py", line 1177, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\ComfyUI\comfy\sample.py", line 82, in sample
    models, inference_memory = get_additional_models(positive, negative, model.model_dtype())
  File "D:\ComfyUI\comfy\sample.py", line 56, in get_additional_models
    control_nets = set(get_models_from_cond(positive, "control") + get_models_from_cond(negative, "control"))
  File "D:\ComfyUI\comfy\sample.py", line 50, in get_models_from_cond
    if model_type in c[1]:
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 985, in __contains__
    raise RuntimeError(
RuntimeError: Tensor.__contains__ only supports Tensor or scalar, but you passed in a <class 'str'>.

**Comment by comfyanonymous** [comment]
can I see your workflow?

**Comment by Clelstyn** [comment]
<img width="1546" alt="issue" src="https://github.com/comfyanonymous/ComfyUI/assets/141990218/db1e9bd8-e564-43c8-90a4-bec9c9daf086">

I've had the same problem since the last update.
This is a simple inpaint workflow using the DetailerForEach node.
When I run it after specifying the mask region, I get the same error in the DetailerForEach node.

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/127

Coincidentally, I encountered the same issue report. 
However, this is a case where text is connected where conditioning should be linked. 
Due to the type restrictions, the connection itself should not have occurred. 

I can't quite grasp how such an event unfolded. 
As a double-check, I attempted to establish a connection between the `derfuu`'s `Text box` node and my `ToBasicPipe` node, and I confirmed that the connection was not allowed as expected.

**Comment by tzekeong** [comment]
> [ltdrdata/ComfyUI-Impact-Pack#127](https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/127)
> 
> Coincidentally, I encountered the same issue report. However, this is a case where `STRING` output is connected where `CONDITIONING` should be linked. Due to the type restrictions, the connection itself should not have occurred.
> 
> I can't quite grasp how such an event unfolded. As a double-check, I attempted to establish a connection between the `derfuu`'s `Text box` node and my `ToBasicPipe` node, and I confirmed that the connection was not allowed as expected.
> 
> EDIT: It is happend from `Text to Conditioning` custom node.

Indeed, seems like happened from `Text to Conditioning` custom node.

Thank you @ltdrdata
