### ISSUE TITLE
Black images are output at random.

### ISSUE THREAD

**Issue by rabidcopy** [comfyanonymous/ComfyUI#1402]
~~Ever since the recent commits concerning VAE precision, there has been a tendency for black images to be output at random despite not ever forcing the VAE to be run in fp16 and it claiming on startup that the VAE precision is fp32. When this happens restarting ComfyUI doesn't always fix it and it never starts off putting out black images but once it happens it is persistent. This was never a problem previously on my setup or on other inference methods such as Automatic1111.~~

```
python main.py --normalvram --preview-method auto --use-quad-cross-attention --dont-upcast-attention --disable-smart-memory
Total VRAM 4096 MB, total RAM 15944 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 AMD Radeon RX 570 Series : native
VAE dtype: torch.float32
disabling upcasting of attention
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Total VRAM 4096 MB, total RAM 15944 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 AMD Radeon RX 570 Series : native
VAE dtype: torch.float32
```

```
home/rabid/Documents/ComfyUI/nodes.py:1274: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
```

~~Edit: Even stranger I can switch to a similar model, not have the black image issue, then switch back to the model it started on and the issue remains.~~

~~Edit2: But sometimes swapping back and forth DOES resolve it for the model that put out a black image. I considered that maybe there's a problem with the model and a NaN was being produced, but then I ran the exact prompt/seed from the history again on a black image and it didn't put out a black image.~~

Edit3: see https://github.com/comfyanonymous/ComfyUI/issues/1402#issuecomment-1703937660

**Comment by comfyanonymous** [comment]
Are you on the latest pytorch ROCm nightly?

**Comment by rabidcopy** [comment]
> Are you on the latest pytorch ROCm nightly?
`local/python-pytorch-opt-rocm 2.0.1-5`
```
(venv) [rabid@rabid-ms7b87 ComfyUI]$ pip list | grep -i torch
open-clip-torch           2.7.0
pytorch-lightning         1.9.4
pytorch-triton-rocm       2.0.2
torch                     2.0.1
torchdiffeq               0.2.3
torchmetrics              1.0.1
torchsde                  0.2.5
torchvision               0.15.2a0
```

I haven't updated ROCM or PyTorch and am still on ROCM 5.4.3-2 on ArchLinux.

**Comment by rabidcopy** [comment]
Adding on and trying to provide more info, the commit that this starts happening where I can get black images is somewhere **after** https://github.com/comfyanonymous/ComfyUI/commit/0b6cf7a5589351f677f76a6504850d5702c40d08, this commit and those before it never suffer from this black image issue. Git pulling to latest master from this commit lead to an immediate black image output.

**Comment by rabidcopy** [comment]
I think I've narrowed it down to this change. https://github.com/comfyanonymous/ComfyUI/commit/ec96f6d03a0a21051811f5dbd7f90405f18c319a

After this commit when loading these particular models it will report this: (they are niche models that use v-prediction)
```
model_type V_PREDICTION
adm 0
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
missing {'cond_stage_model.text_projection', 'cond_stage_model.logit_scale'}
loading new
loading new
100%|████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:58<00:00,  3.68s/it]
/home/rabid/Documents/ComfyOmega/nodes.py:1269: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
```
(This was getting a black image on this commit right after swapping models.)

I cannot reproduce black images or things being reported as missing in the console on commit https://github.com/comfyanonymous/ComfyUI/commit/30eb92c3cbe0e0dfa442d452b5f1187c654e572e.

**Comment by comfyanonymous** [comment]
I don't think it's that commit because only SDXL actually uses: text_projection

**Comment by rabidcopy** [comment]
> I don't think it's that commit because only SDXL actually uses: text_projection

Strange.. these are SD 1.5 based models though, so why is it caring to report that it doesn't have those things?

**Comment by rabidcopy** [comment]
Just throwing ideas out, maybe an unexpected interaction between 30eb92c and e9469e732d8c84048dcf4c94604607c92e5297df as I'm using `--disable-smart-memory`? (can't test now, actually have to leave until later tonight/tomorrow morning)

**Comment by rabidcopy** [comment]
Haven't been able to reproduce the issue on either commit this morning after a complete power cycle of my computer. So I'm starting to think there was some sort of lingering VRAM or RAM issue after pushing my card to the limit for a good part of the day. I'll leave this issue open for now just in case I git pull to latest master and the issue miraculously comes back. And if it doesn't I'll just close it.

Sorry for the trouble. Just want to say I really appreciate your work on this repo. It has proven to be a much better and less sluggish option for inference on my system.

**Comment by NeedsMoar** [comment]
Since you're not on NVidia
1) If you have XMP ram (and running it at one of the XMP speeds instead of its true clock) it tends to accumulate errors slowly depending on the stick and manufacturer but I don't think that's the cause unless:
2) If you've been using the same VAE and not maxing out system ram all day, Linux "cached" memory (I don't know what the subsystem is called, on Windows it's more agressive and is more the interaction between "standby" and Superfetch) would probably be able to keep something relatively small like the VAE in memory the whole time.  If you're getting a bunch of bit-flips because of an unstable stick that normally wouldn't have many issues if it was being refreshed constantly something may have hit the wrong spots in the VAE and shoved a NaN or +/- 0 or +/- inf in there that's propagating and screwing things up fairly often...  Doesn't take much for floating point errors to propagate and explode either.  

If it happens again you could try clearing that (I don't know the command, sorry) or just forcing it to clear by loading other stuff in sequence.   Or the reboot will do it obviously.  Then you can run memtest and figure out which stick of ram is messing up or just clock all of it down to base speed or halfway between XMP and base or whatever you think it'll manage and let the lower latency make up for the lower clocks.   It's not likely to be anything going on with the GPU unless it's getting ready to die completely since the vae won't be kept there in all probability, almost certainly not for that long.
