### ISSUE TITLE
[Feature Request] Ability to set Checkpoint directory via Commandline

### ISSUE THREAD

**Issue by zabinzsur** [comfyanonymous/ComfyUI#15]
To avoid duplicating Checkpoints when you have multiple UIs installed (such as Automatic1111 install and ConfyUI).

**Comment by comfyanonymous** [comment]
Yeah I'll be adding that.

In the meantime you can add a symlink to the auto1111 checkpoints folder in models/checkpoints/ and it should work.

**Comment by andzejsp** [comment]
For binbows users i reccomend doing this, to save space, but make sure your comfy UI and other models are on the same hard drive, otherwise it wont work.

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mklink

Linking models folder to destination from source:

Open CMD with admin rights (press right mouse button - run as administrator

![image](https://user-images.githubusercontent.com/80409979/224986282-41a7da1f-c45e-4408-82c8-ad9b685883cb.png)


Then write this (my specific case):

```
mklink /D E:\VBA_PROJECTS\Git\ComfyUI\models\checkpoints E:\VBA_PROJECTS\Git\stable-diffussion-webui-automatic\models\Stable-diffusion
```

```
mklink /D <destination> <source>
```

Have fun!
