### ISSUE TITLE
Question: why doesn't the VAE decoder generate un upscaled image

### ISSUE THREAD

**Issue by amida47** [comfyanonymous/ComfyUI#1525]
looking at the SDXL paper we see illustration of SDXL pipeline
![image](https://github.com/comfyanonymous/ComfyUI/assets/49212088/f6b8ac99-70fb-4120-8afe-6f2b10b5371d)
my question is why doesn't the VAE decoder node in comfyui do this (takes low res latent image and ouputs a high res image). 

In comfyui it's input and output are of the same resolution.

I am sure I'm messing something, please help me understand?

**Comment by Piezoid** [comment]
VAE encode/decode are best thought as compression/decompression rather than up-scaling. The VAE removes redundant information in the image, enabling the model to work (and train) faster on that latent representation.

It appears that the confusion stems from this: the size parameters in the `Empty Latent Image` node set the dimension of the resulting image *after* decoding. The actual latent processed by KSampler is 8x8 smaller than that.

There is no VAE encoder in this txt2img pipeline. The inference begins with a 128x128 noisy latent. A img2img pipeline would have: Image[1024x1024] -> Latent[128x128] -> denoise -> Latent[128x128] -> Image[1024x1024]

**Comment by amida47** [comment]
so this node 
![image](https://github.com/comfyanonymous/ComfyUI/assets/49212088/d0e1919d-9ab6-4b2b-9525-a6c34796430f)
is only letting me choose the resolution of the final image, but the comfyui txt2img pipeline works internally with an encoded (compressed) latent representation.

@Piezoid is my understanding correct?
