### ISSUE TITLE
Can't launch ComfyUi

### ISSUE THREAD

**Issue by Axonical** [comfyanonymous/ComfyUI#1530]
I run with CPU
![Screenshot (228).png](https://github.com/comfyanonymous/ComfyUI/assets/145185861/0af11a2a-63fd-4d9a-ac40-186c73ba5daa)

![Screenshot (229).png](https://github.com/comfyanonymous/ComfyUI/assets/145185861/a95462f5-c238-40cb-bb35-4321e0703796)

**Comment by mcmonkey4eva** [comment]
It looks like you have corrupt files in the embedded env? You likely need to delete comfyui and reinstall

**Comment by Axonical** [comment]
I've tried reinstalling it several times but it still doesn't work

**Comment by Axonical** [comment]
> It looks like you have corrupt files in the embedded env? You likely need to delete comfyui and reinstall

I've tried reinstalling it several times but it still doesn't work

**Comment by ltdrdata** [comment]
> > It looks like you have corrupt files in the embedded env? You likely need to delete comfyui and reinstall
> 
> I've tried reinstalling it several times but it still doesn't work

Have you tried redownload the 7z file?

**Comment by Axonical** [comment]
> > > It looks like you have corrupt files in the embedded env? You likely need to delete comfyui and reinstall
> > 
> > I've tried reinstalling it several times but it still doesn't work
> 
> Have you tried redownload the 7z file?

yes I've tried it but it doesn't work

**Comment by ltdrdata** [comment]
> > > > It looks like you have corrupt files in the embedded env? You likely need to delete comfyui and reinstall
> > > 
> > > 
> > > I've tried reinstalling it several times but it still doesn't work
> > 
> > 
> > Have you tried redownload the 7z file?
> 
> yes I've tried it but it doesn't work

This seems to be an issue related to your Windows environment. Do you have any other existing installations of Python?
"We need to check if there might be a conflict caused by another Python installation."
Just try execute the `python` command in the `cmd` window.

If you have an existing Python installation, try uninstalling it. If not, you may need to manually download `Python 3.10` instead of using the portable version and create a `venv` to see if that resolves the issue.

**Comment by Axonical** [comment]
sorry I'm new here, how to create a venv?
