### ISSUE TITLE
Extra_model_paths.yaml writing format

### ISSUE THREAD

**Issue by tuoluogongfang** [comfyanonymous/ComfyUI#1730]
I read question #1664 but, I still won't solve my problem, requesting help!

The file of custom_nodes\xxx\models\..., I want to refer to the file of other paths, how do I write this format in extra_model_paths.yaml.

**Comment by NeedsMoar** [comment]
If you're talking about the models that various extensions download or want you to download and install in some non-standard location like (ex: ComfyUI\custom_nodes\IPAdapter-ComfyUI\ which has ~1GB of models in it, or \ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\ which is 8GB of models on my machine) you can't change those from the YAML file because that isn't supported by their authors for whatever reason
AnimateDiff uses the following a directory deeper than the models directory is to grab the relative models directory from the path of its precompiled version:

```python3
# register motion models folder(s)
folder_paths.folder_names_and_paths[Folders.ANIMATEDIFF_MODELS] = (
    [
        str(Path(__file__).parent.parent / "models")
    ],
    folder_paths.supported_pt_extensions
)
```

where IPAdapterPlus does something more like this:

```python3
class IPAdapterModelLoader:
    @classmethod
    def INPUT_TYPES(s):
        return {"required": { "ipadapter_file": (get_filename_list(MODELS_DIR), )}}
```
which looks promising until you find that MODELS_DIR is defined as:

```python3
MODELS_DIR = os.path.join(os.path.dirname(os.path.realpath(__file__)), "models")
```

Unfortunately you'd need to get all of the authors of those extensions on board with at least allowing load from the other locations so you can manually move them if nothing else.  It's a toss-up for me because I'd personally rather have software wasting space in its own directory tree than doing what some other couple of python extensions have done and apply the linux XDG_* path specs _in a completely incorrect manner_ (aka how they were written) to software running on Windows, but at the same time I'd rather it just be done right.  :D   I uninstalled around 7 different open source image editing programs months back because they'd installed a total of 20 pythons on my system of different versions all local to their install and each one spamming temp / cache files into a different spot.  Comfy itself has been good about not doing that so I'd rather not see anyone get the brilliant idea to start putting things under users because it's "central".

Otherwise if you just want to redirect downloaded things normally under ComfyUI\models;  some of the extensions keep their models in there too, but I don't know if they'll honor the YAML or not;  that's what the yaml is for right now.   If you open the file locally it explains exactly what needs to be changed but I'm afraid it won't do what you want at the moment.

**Comment by tuoluogongfang** [comment]
Thank you!
