### ISSUE TITLE
i can not see picture in the web

### ISSUE THREAD

**Issue by oceanusXXD** [comfyanonymous/ComfyUI#1919]
I can't see the picture I generated on web, although I can see them in the output folder,nd there are no error messages.

**Comment by txirrindulari** [comment]
> I can't see the picture I generated on web, although I can see them in the output folder,nd there are no error messages.

Make sure you are using de vae decode node, from the latent output of the ksampler node + VAE, and outputting to a preview image node.

**Comment by dabaonidetou** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/116332761/af8137d9-0852-499d-bb8d-c0bae6fa13eb)
![image](https://github.com/comfyanonymous/ComfyUI/assets/116332761/9906d0a1-0820-40f9-bc9b-06f681347fa4)
I've tried everything that can load images, but it still doesn't work

**Comment by txirrindulari** [comment]
> ![image](https://user-images.githubusercontent.com/116332761/280979551-af8137d9-0852-499d-bb8d-c0bae6fa13eb.png) ![image](https://user-images.githubusercontent.com/116332761/280979659-9906d0a1-0820-40f9-bc9b-06f681347fa4.png) I've tried everything that can load images, but it still doesn't work

Check if in comfyui manager Preview method is set to: none and change it to AUTO

**Comment by dabaonidetou** [comment]
> > ![image](https://user-images.githubusercontent.com/116332761/280979551-af8137d9-0852-499d-bb8d-c0bae6fa13eb.png) ![image](https://user-images.githubusercontent.com/116332761/280979659-9906d0a1-0820-40f9-bc9b-06f681347fa4.png) I've tried everything that can load images, but it still doesn't work
> 
> Check if in comfyui manager Preview method is set to: none and change it to AUTO

Yes, I have set it to AUTO as well.

**Comment by NeedsMoar** [comment]
The save image node and preview image nodes doesn't use the previewer, it's the fully decoded image from VAE.   Try expanding your preview / save nodes into larger squares so they have room for the image to show up, they don't seem to auto-size anymore.  

You don't need a preview node attached to the same chain as a save image node since they'll both show the same image.  The preview node is for spots where you don't want to save automatically like mid-workflow.  

Same goes for preview with AUTO or TAESD  or whatever on the sampler nodes, you need to expand the bottom of them so there's a free square area you can see the image in or it'll assume you're hiding it on purpose and not show anything.  

If you install ComfyUI-Custom-Nodes you should also be able to go to the settings gear on the top of the menu and enable a "preview image on menu" or similar that will show the preview from whatever generation step is currently running.

**Comment by rachelcenter** [comment]
> The save image node and preview image nodes doesn't use the previewer, it's the fully decoded image from VAE. Try expanding your preview / save nodes into larger squares so they have room for the image to show up, they don't seem to auto-size anymore.
> 
> You don't need a preview node attached to the same chain as a save image node since they'll both show the same image. The preview node is for spots where you don't want to save automatically like mid-workflow.
> 
> Same goes for preview with AUTO or TAESD or whatever on the sampler nodes, you need to expand the bottom of them so there's a free square area you can see the image in or it'll assume you're hiding it on purpose and not show anything.
> 
> If you install [ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts) you should also be able to go to the settings gear on the top of the menu and enable a "preview image on menu" or similar that will show the preview from whatever generation step is currently running.
> 
> Edit: Fixed custom node name. That will also give you an "image feed" strip you can position wherever that shows completed images and lets you click for full screen. Keep in mind TAESD previews and menu previews will slow down generation although judging by your speeds that isn't something I'd worry about terribly.

i tried to install it, but im nto seeing "preview image on menu" or similar in the menu. shrug. maybe i installed it wrong
