### ISSUE TITLE
Inpainting + Img2img

### ISSUE THREAD

**Issue by Mindspherical** [comfyanonymous/ComfyUI#1956]
I'm wondering if there's a way to setup inpainting in Comfy that looks at what's under as masked area with a given init strength? 

The use case is essentially to allow the inpaint to be somewhat guided by the existing image, or by a patch-match image expansion (for example) to allow for better inpainting results.

**Comment by jn-jairo** [comment]
Use the "Set Latent Noise Mask" and a lower denoise value in the KSampler, after that you need the "ImageCompositeMasked" to paste the inpainted masked area into the original image, because the VAEEncode don't keep all the details of the original image, that is the equivalent process of the A1111 inpainting, and for better results around the mask you can convert the mask to image, blur it using the "ImageBlur" and convert it back to mask.

**Comment by Mindspherical** [comment]
Thanks @jn-jairo - I just tried this and the Set Latent Noise Mask seems to just pass through the entire image - it doesn't seem to be applying the mask. I've attached my workflow if you felt like having a quick look. Appreciate it either way!

[inpaint (2).json](https://github.com/comfyanonymous/ComfyUI/files/13342698/inpaint.2.json)

**Comment by jn-jairo** [comment]
@Mindspherical you took the "lower denoise" too literally, 0.01 will do nothing, I made a new complete workflow in the way I use it.

Original image:
![the-mona-lisa](https://github.com/comfyanonymous/ComfyUI/assets/5104869/2849a208-efe2-4b14-81ce-d52b006c9020)

Mask:
![ComfyUI_temp_jaoqg_00001_](https://github.com/comfyanonymous/ComfyUI/assets/5104869/ca33d81b-aec8-41aa-beca-4eec6a78e821)

Prompt: woman wearing a scarf

With denoise 0.75
![ComfyUI_temp_dioca_00001_](https://github.com/comfyanonymous/ComfyUI/assets/5104869/5004810f-7c8b-4d3b-960a-3af4d8f07014)

With denoise 0.5
![ComfyUI_temp_dioca_00002_](https://github.com/comfyanonymous/ComfyUI/assets/5104869/ad944133-7ddd-4ffd-9100-fa769939408b)

The result image has the workflow.

You need to have enough denoise to do the changes you want to.

**Comment by Mindspherical** [comment]
Thanks @jn-jairo ! I actually tried 0.99 denoise to begin with and found no difference. Will review your workflow though, appreciate it!

**Comment by Mindspherical** [comment]
Hm, it's interesting - your method works well with a straight checkpoint, but if I load a custom UNET this approach seems to result in little to no change to the image.

**Comment by Mindspherical** [comment]
E.g. here's a workflow which includes the 0.1 inpaint UNET (from https://huggingface.co/diffusers/stable-diffusion-xl-1.0-inpainting-0.1/tree/main/unet) 
[Uploading inpaint-with-unet.json…]()

I go from this output, using a checkpoint:
![image](https://github.com/comfyanonymous/ComfyUI/assets/117719106/650dc247-6f0d-4d2a-8da9-ac8ac68e22e2)

To this output, using the inpaint UNET:
![image](https://github.com/comfyanonymous/ComfyUI/assets/117719106/4eb24df2-ace5-4d15-9fe3-5273ad0ecff7)

All the inpaint unet seems to do is cook the masked area, which is strange considering it does that even up to 0.99 denoise!

Notably, if I use the VAE Encode for inpainting which completely ignores what's under the mask, then the inpaint UNET works great for the most part. However, it falls over on occasion, which is why I'd like to pass through some of the underlying image - and be able to dial that up and down.

**Comment by ltdrdata** [comment]
If you are using an `inpainting model` and do not want to set the denoise to 1.0, your issue seems to be related to this problem.
https://github.com/comfyanonymous/ComfyUI/issues/1186

**Comment by jn-jairo** [comment]
Oh, I saw something about it in another thread, try the VAEEncodeForInpaint instead of the "Set Latent Noise Mask" maybe it helps, I don't use models made for inpainting, but I think that should help.

**Comment by Mindspherical** [comment]
Thanks all - I didn't spot that other issue. It does seem like there's an issue in that we can't use inpaint models in this way, hoping it's addressed sometime soon 🙂

**Comment by suede299** [comment]
I spent a few days trying to achieve the same effect with the inpaint model. It turns out that doesn't work in comfyui. The custom noise node successfully added the specified intensity of noise to the mask area, but even when I turned off ksampler's add noise, it still denoise the whole image, so I had to add "Set Latent Noise Mask", Add the start step of the sampler. It ended badly.
To achieve a similar effect as in auto1111, you can only use the detailer sampler (impactpack) noise mask and a generic model. However, the input to the sampler is image, not latent.
