### ISSUE TITLE
Once `IS_CHANGED` is defined within the custom nodes, how to disable to prevent update again?

### ISSUE THREAD

**Issue by Trung0246** [comfyanonymous/ComfyUI#1962]
Since for some reason when applying same values over and over again upon returning `IS_CHANGED` the entire graph still being updated.

The thing is there's some custom nodes that are not deleted within the UI (and also does not connect to anything), this would cause the `is_changed != is_changed_old` to fails since `is_changed_old` is always an empty string for these standalone nodes, which cause the check to fails since `[] != None`.

Which is how to do `IS_CHANGED` properly to allows updates or prevent update? Or is this a bug?

**Comment by jn-jairo** [comment]
Tip, check if the IS_CHANGED is throwing an exception, because when there is an exception the code ignores the exception and mark this node as changed, I spent hours looking for it in a custom node of mine.

**Comment by Trung0246** [comment]
The code is very minimal, I can guarantee the function do nothing but returning `True`.

**Comment by ltdrdata** [comment]
> The code is very minimal, I can guarantee the function do nothing but a single line of returning `True` during testing, which means exception is out of the question, which makes the entire thing weirder.

While the exact situation is not clear, one thing to note is that, despite its name, `IS_CHANGED` should be a function that returns a **hash value** rather than a predicate.

**Comment by Trung0246** [comment]
> > The code is very minimal, I can guarantee the function do nothing but a single line of returning `True` during testing, which means exception is out of the question, which makes the entire thing weirder.
> 
> While the exact situation is not clear, one thing to note is that, despite its name, `IS_CHANGED` should be a function that returns a **hash value** rather than a predicate.

Oh sha1 or something?

**Comment by ltdrdata** [comment]
> > > The code is very minimal, I can guarantee the function do nothing but a single line of returning `True` during testing, which means exception is out of the question, which makes the entire thing weirder.
> > 
> > 
> > While the exact situation is not clear, one thing to note is that, despite its name, `IS_CHANGED` should be a function that returns a **hash value** rather than a predicate.
> 
> Oh sha1 or something? Since I cannot figure which hash type should be given.
> 
> EDIT: looking at the some samples usage with the code, looks like it's sha256. Guess I'll return a random sha256 hash then.
> 
> Also looks like more debugging and I probably found out the root cause. Will probably close this for now.

The term `hash` does not refer to a specific format of hash. 

For example, assuming the input is an `image`, if a tensor with the same data is accidentally generated and passed from the front of the `image` input due to a rerun, if there is no defined `IS_CHANGED`, the input is assumed to have changed, and the current node is rerun unconditionally. However, if a suitable `hash` is created and returned for the image tensor in `IS_CHANGED`, it will only be executed when the image has actually changed.

In essence, the comparison is performed by comparing the values returned by `IS_CHANGED` currently with the values returned by `IS_CHANGED` previously, so it just needs to be a comparable form.

This makes possible the trick with `float("nan")`. Returning this will always make the comparison false, resulting in a rerun every time.
