### ISSUE TITLE
Click queue prompt, server stopped and reconnecting

### ISSUE THREAD

**Issue by Wenxuanxi** [comfyanonymous/ComfyUI#2016]
Hi, guys, I took 4 hours to deploy my comfyui on my google cloud instance.
When I installed and updated all models, I was excited to see my first picture based comfyui.
But when I clicked the queue prompt button, it appeared the box with reconnecting, when I switched to the cmd window, nothing happend except got promt and pause.
I tried run nvidia and run cpu, both did same.
Anyone, could you please tell me what I should do ....

**Comment by Lodjuret** [comment]
Having a similiar error.

I'm on linux and when clicking queue my terminal closes. No errors and can't find any logs. This is a clean install and running default workspace.

**Comment by microvswind** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/103630540/a5727851-9e83-487a-968d-c3057ec28024)

**Comment by camoody1** [comment]
I'm getting this exact same issue on a fresh install of the portable installation.

Fresh Windows 11 installation
Nvidia RTX 3060 12GB
32GB RAM

I was able to get it to run successfully once, but then I changed the model in the checkpoint node (to Juggernaught v7) and it hasn't worked since. The workflow seems to get stuck with the highlight on the initial checkpoint node and the cmd window just says "pause".

CMD output from server start:
---------------------------------_
H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-12-02 20:29:38.930459

Prestartup times for custom nodes:
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12288 MB, total RAM 32695 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints H:\Stable_Diffusion_Models\models/Stable-diffusion
Adding extra search path configs H:\Stable_Diffusion_Models\models/Stable-diffusion
Adding extra search path vae H:\Stable_Diffusion_Models\models/VAE
Adding extra search path loras H:\Stable_Diffusion_Models\models/Lora
Adding extra search path loras H:\Stable_Diffusion_Models\models/LyCORIS
Adding extra search path upscale_models H:\Stable_Diffusion_Models\upscale_models
Adding extra search path upscale_models H:\Stable_Diffusion_Models\models/BSRGAN
Adding extra search path upscale_models H:\Stable_Diffusion_Models\models/ESRGAN
Adding extra search path upscale_models H:\Stable_Diffusion_Models\models/GFPGAN
Adding extra search path upscale_models H:\Stable_Diffusion_Models\models/LDSR
Adding extra search path upscale_models H:\Stable_Diffusion_Models\models/RealESRGAN
Adding extra search path upscale_models H:\Stable_Diffusion_Models\models/SwinIR
Adding extra search path embeddings H:\Stable_Diffusion_Models\models/Embeddings
Adding extra search path hypernetworks H:\Stable_Diffusion_Models\models/hypernetworks
Adding extra search path controlnet H:\Stable_Diffusion_Models\models/ControlNet
Bmad-DirtyUndoRedo Loaded.
Skip H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Bmad-DirtyUndoRedo module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
### Loading: ComfyUI-Impact-Pack (V4.38)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
### Loading: ComfyUI-Manager (V1.6.1)
### ComfyUI Revision: 1768 [b2517b4c] | Released on '2023-12-02'
[tinyterraNodes] Loaded
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 198 nodes successfully.

        "Everything you've ever wanted is on the other side of fear." - George Addair


Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Bmad-DirtyUndoRedo
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\OneButtonPrompt
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.1 seconds: H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.4 seconds: H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.8 seconds: H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   1.0 seconds: H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.6 seconds: H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE

H:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable>pause
Press any key to continue . . .

**Comment by DDWUDI** [comment]
我也是这样的错误，有人知道原因吗。
![fdf7d5cd70d4ee7b6bca86127adc25c](https://github.com/comfyanonymous/ComfyUI/assets/80200310/34e10c37-d7df-434e-940d-93af10612ae9)

**Comment by d3c1m470r** [comment]
this is the second ui im trying to use for local generation and it does the same error for me.
hours wasted of my life im sick of these terrible releases which dont work for a lot of people rly

**Comment by dsegoviap** [comment]
I have the same problem. Does anyone know how to fix it?

**Comment by ltdrdata** [comment]
Usually, this issue occurs due to insufficient memory resources, leading to a forced termination. Monitor the usage of RAM/VRAM to investigate.

**Comment by camoody1** [comment]
> I have the same problem. Does anyone know how to fix it?

I swear to God, my fix for this issue was to change my Windows Swap File settings to allow Windows to manage the swap file for each drive. And this was on a fresh Windows 11 reinstall. By default, my swap drive was under 100MB. After I clicked the other option, Windows assigned, like, 30GB to be a swap drive. That error immediately stopped for me.

**Comment by dsegoviap** [comment]
> > I have the same problem. Does anyone know how to fix it?
> 
> I swear to God, my fix for this issue was to change my Windows Swap File settings to allow Windows to manage the swap file for each drive. And this was on a fresh Windows 11 reinstall. By default, my swap drive was under 100MB. After I clicked the other option, Windows assigned, like, 30GB to be a swap drive. That error immediately stopped for me.

Gracias amigo! esa fue la solucion. I change my Window Swap File up to 32GB.

**Comment by camoody1** [comment]
> Thanks friend! that was the solution. I change my Window Swap File up to 32GB.

Wonderful! I'm glad that fixed it for you, also! Such an odd setting for Windows to mess up.

**Comment by hong2610** [comment]
> > > 我也遇到了同样的问题。有人知道该怎么解决吗？
> > 
> > 
> > 我发誓，我解决这个问题的方法是更改​​我的 Windows 交换文件设置，以允许 Windows 管理每个驱动器的交换文件。这是在重新安装 Windows 11 时发生的。默认情况下，我的交换驱动器小于 100MB。在我单击另一个选项后，Windows 分配了大约 30GB 作为交换驱动器。那个错误立即停止了。
> 
> 谢谢朋友！这就是解决方案。我将窗口交换文件更改为 32GB。

Could you please tell me how to do it? I am a computer novice and I have the same problem.

**Comment by a-gridnev** [comment]
> > > > 我也遇到了同样的问题。有人知道该怎么解决吗？
> > > 
> > > 
> > > 我发誓，我解决这个问题的方法是更改​​我的 Windows 交换文件设置，以允许 Windows 管理每个驱动器的交换文件。这是在重新安装 Windows 11 时发生的。默认情况下，我的交换驱动器小于 100MB。在我单击另一个选项后，Windows 分配了大约 30GB 作为交换驱动器。那个错误立即停止了。
> > 
> > 
> > 谢谢朋友！这就是解决方案。我将窗口交换文件更改为 32GB。
> 
> Could you please tell me how to do it? I am a computer novice and I have the same problem.

right click on start button -> Search -> type "performance" -> select "Adjust the appearance and performance of  Windows" -> go to tab "Advanced" -> in block "Virtual memory" press to "Change" -> select "System managed size" radio button and then press "Set" -> reboot your PC

<details>
<summary> screenshots </summary>

![2024-08-04_231134](https://github.com/user-attachments/assets/33781d9e-8e97-48f9-8bcd-fdf053924405)

![2024-08-04_231153](https://github.com/user-attachments/assets/e6ca74e1-f04d-408e-8f36-9463cc8107e3)

![2024-08-04_231210](https://github.com/user-attachments/assets/3bbd687a-1cc0-48f7-a699-23a09c04b5db)

![2024-08-04_231220](https://github.com/user-attachments/assets/b75c0021-3744-4256-90d5-a493d1d95345)

</details>

**Comment by BuRZone** [comment]
I solved this problem by shutting down processes and increasing the amount of free RAM

**Comment by mhidoart** [comment]
> > I have the same problem. Does anyone know how to fix it?
> 
> I swear to God, my fix for this issue was to change my Windows Swap File settings to allow Windows to manage the swap file for each drive. And this was on a fresh Windows 11 reinstall. By default, my swap drive was under 100MB. After I clicked the other option, Windows assigned, like, 30GB to be a swap drive. That error immediately stopped for me.

it works for me !! thanks!!
![fixComfyui-Swap](https://github.com/user-attachments/assets/f130d29b-f1a0-4f3f-ac31-b5d06431ba26)

**Comment by camoody1** [comment]
@mhidoart Glad it could help! I was so surprised when it fixed my issue!

**Comment by nothingness6** [comment]
> > > > > 我也遇到了同样的问题。有人知道该怎么解决吗？
> > > > 
> > > > 
> > > > 我发誓，我解决这个问题的方法是更改​​我的 Windows 交换文件设置，以允许 Windows 管理每个驱动器的交换文件。这是在重新安装 Windows 11 时发生的。默认情况下，我的交换驱动器小于 100MB。在我单击另一个选项后，Windows 分配了大约 30GB 作为交换驱动器。那个错误立即停止了。
> > > 
> > > 
> > > 谢谢朋友！这就是解决方案。我将窗口交换文件更改为 32GB。
> > 
> > 
> > Could you please tell me how to do it? I am a computer novice and I have the same problem.
> 
> right click on start button -> Search -> type "performance" -> select "Adjust the appearance and performance of Windows" -> go to tab "Advanced" -> in block "Virtual memory" press to "Change" -> select "System managed size" radio button and then press "Set" -> reboot your PC
> screenshots

This one works! Thanks!

**Comment by allstar1945** [comment]
mine still reconnecting, i thought my GPU the promblem, am i wrong, i have 4070 12GB VRAM and 16GB RAM, any help?, couldn't find any help on google
