### ISSUE TITLE
Utilize SWAP memory?

### ISSUE THREAD

**Issue by djbritt** [comfyanonymous/ComfyUI#2023]
When comfyui launches, it doesn't include SWAP memory in total memory. I have a 20gb swapfile mounted that I'd like to make available to comfyui. Is this possible?

**Comment by NeedsMoar** [comment]
Swap is managed by the OS and isn't included in total available because it doesn't behave like ram and applications don't need to know about it and can't really rely on it, since it usually contains things that couldn't be discarded (so there's not really any way to free memory from it to except by whatever program was unfortunate enough to have part of its data placed there in the first place).
