### ISSUE TITLE
Coding question

### ISSUE THREAD

**Issue by drago87** [comfyanonymous/ComfyUI#2024]
Is there a way to make sure a node is run each time you generate a image? i'm making a node that reads how meny png files there is in a  folder (the output folder) but it is only running once after a restart or if i change to folder.

**Comment by jn-jairo** [comment]
This comment explains how to make a node run everytime https://github.com/comfyanonymous/ComfyUI/issues/1962#issuecomment-1809574013

**Comment by drago87** [comment]
So if i understand it i only need to add a
`is_changed != None` to the node?

**Comment by jn-jairo** [comment]
It is a method called IS_CHANGED like this https://github.com/comfyanonymous/ComfyUI/blob/72741105a687c67137eb5d7a38840b8373d82e61/nodes.py#L435

And as the comment says, if you return `float("nan")` in this method, it will always execute the node.

The ComfyUI compare the return of this method before executing, and if it is different from the previous execution it will run that node again, and because of that the `float("nan")` trick works. Returning this will always make the comparison false, resulting in a rerun every time.

So something like this should work:

```python
def IS_CHANGED(self, **kwargs):
    return float("nan")
```

I am on my phone so I can't check it properly, but if I remember correctly that is the code.

**Comment by drago87** [comment]
Got it to work i'm not 100% sure what fixed it but i added a passture for the `latent` and used that to trigger the `IS_CHANGED`

```
class file_padding:
    def __init__(self):
        pass
    
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "path": ("STRING",{
                    "multiline": False,
                    "default": "./ComfyUI/output/"
                }),
                "padding": ("INT", {
                    "default": 4,
                    "min": 1,
                    "max": 10,
                    "step": 1,
                    "display": "number"
                }),
                "latents": ("LATENT", {
                    "forceInput": True
                })
            }
        }
    RETURN_TYPES = ("STRING","LATENT")
    RETURN_NAMES = ("Number of Images (as str)","Latent Passtrue")
    
    FUNCTION = "run"
    
    CATEGORY = "DragosNodes"
    
    def run(self, path, padding, latents):
        ##print("init "+str(path))
        if (path[-1]!="/"):
            path = path+"/"
        ##print("after "+ str(path))
        ##print(str(glob.glob(path+"*.png")))
        padding_length=len(glob.glob(path+"*.png"))
        added_padding=len(str(padding_length))
        if padding == 1:
        
            lenght = str(padding_length)
            return(lenght,latents)
        else:
            lenght = ""
            x = 1
            while len(lenght) < added_padding:
                lenght = lenght+"0"
                x+=1
            #print("test " +lenght)
            lenght = lenght + str(padding_length)
            #print(lenght)
            return(lenght,latents)
            
            
    @classmethod       
    def IS_CHANGED(s, latents):
        image_path = folder_paths.get_annotated_filepath(latents)
        m = hashlib.sha256()
        with open(image_path, 'rb') as f:
            m.update(f.read())
        return(float("nan"))
```

**Comment by schoenid** [comment]
Still a problem for many ...

I had a similar problem, where my custom node did not correctly update it's output widget.
Instead of showing the correct output data in the Resolution Calculator, it did show data from other nodes, like from the first or second "Any Display"

![Image](https://github.com/user-attachments/assets/750597c2-9455-4a65-bb46-ad6baeca314d)

I simply had to add:
```
    def IS_CHANGED(s, megapixel, modeltype, aspect_ratio, keep_original, width, height):
        return float("nan")
```
for any value who can change.

The image shows, that even my "Anydisplay" had some problems with it.
Even here, the followin lines helped me:
```
    def IS_CHANGED(s, source):
        return float("nan")
```

![Image](https://github.com/user-attachments/assets/5f361a56-203a-40fb-8f5f-a68a4bdb8c19)

So this has to be done for every node who can alter it's values, otherwise the risk is high, to get wrong data.

BTW: Is there any documentation about that?
(https://docs.comfy.org/custom-nodes/overview a.f. is not really helpful ...)
