### ISSUE TITLE
SaveAnimatedWEBP - Change fps input type from float to int

### ISSUE THREAD

**Issue by halr9000** [comfyanonymous/ComfyUI#2070]
The new SVD node, as well as many other animation nodes I've checked out all accept INT, yet the new webp node wants a float. Pretty sure that's not needed, can you change the type?

![image](https://github.com/comfyanonymous/ComfyUI/assets/18482/7774fbf1-065a-4409-b377-88b155f290c9)

![image](https://github.com/comfyanonymous/ComfyUI/assets/18482/5c693213-1aad-413e-a345-e9d3e58f91cb)

**Comment by levicki** [comment]
Actually video frame rates are defined as fractional values (numerator / denominator).

So to be able to output 29.97 FPS (30000 / 1001) or 23.976 FPS (24000 / 1001) you want to have a float input box everywhere.

**Comment by halr9000** [comment]
> Actually video frame rates are defined as fractional values (numerator / denominator).
> 
> So to be able to output 29.97 FPS (30000 / 1001) or 23.976 FPS (24000 / 1001) you want to have a float input box everywhere.

ok cool, so can you fix everything else please? :p 

I am open to solutions here which don't require me writing js or py. I know there's lots of toolbox custom node packs and some do conversions and math. But nothing I have on hand now can actually to from int to float or vice versa. I see several that deal with strings, or even casting strings to ints. 🤷‍♂️ 

all I wanna do here is share frame rate setting across many nodes in a workflow when it gets complicated.

**Comment by levicki** [comment]
> ok cool, so can you fix everything else please? :p

I am not the maintainer, just one of the many users of ComfyUI and I was only explaining that fractional frame rates are valid input and should be acceptable for the final output video file, WebP or otherwise.

> all I wanna do here is share frame rate setting across many nodes in a workflow when it gets complicated.

Then perhaps that's how you should have framed your issue to begin with?

I am pretty sure you could do that with a [custom node](https://github.com/comfyanonymous/ComfyUI/blob/master/custom_nodes/example_node.py.example).

Something like this perhaps:
![image](https://github.com/comfyanonymous/ComfyUI/assets/16415478/40b191a9-1f2f-4c25-abf8-4ae70427b7e2)

**Comment by levicki** [comment]
@halr9000 You can install [this custom node pack](https://github.com/WASasquatch/was-node-suite-comfyui), it has nodes for number conversion.

**Comment by halr9000** [comment]
> @halr9000 You can install [this custom node pack](https://github.com/WASasquatch/was-node-suite-comfyui), it has nodes for number conversion.

Ooh, great find thanks.
