### ISSUE TITLE
[FEATURE REQUEST] Reorder individual nodes within the Group Node

### ISSUE THREAD

**Issue by alessandroperilli** [comfyanonymous/ComfyUI#2118]
The new `Group Node` capability is really cool. I wanted a long time for this. 

The problem is that the order of the inputs and outputs seems arbitrarily decided and there's no way to change it.

For example, I want to aggregate the following two nodes:

<img width="576" alt="Screenshot 2023-11-30 at 23 24 35" src="https://github.com/comfyanonymous/ComfyUI/assets/9775949/7c57d771-5f9f-462b-a3b7-f943dec6a72a">

But I also want to maintain the vertical order of their pins. Instead, the group node insists on arranging the pins in this way:

<img width="968" alt="Screenshot 2023-11-30 at 23 24 53" src="https://github.com/comfyanonymous/ComfyUI/assets/9775949/36b466d0-1d26-43d6-b5dd-ab8d7a1882b9">

If there was a way to rearrange the order of the individual nodes within the group node or, even better, the individual pins, that would be much more manageable.

Thank you!

**Comment by cbaoth** [comment]
Just for the record, since I just stumbled upon this feature (a bit late to the game) and this should work now as far as I can tell:

1. Select two prompt nodes Combine, right click "Convert to Group Node":
![image](https://github.com/user-attachments/assets/cc992f01-4a4f-45bc-be08-8eadace3ee93)

2. Select new Group Node, right click "Manage Group Node":
![image](https://github.com/user-attachments/assets/1aff3ca7-175b-4ada-beb7-650a08c71d33)

3. Modify the Group Node node order, their inputs, widgets, and outputs:
   1. Select the Group Node you want to modify
   2. Rearrange the nodes, which will also rearrange the inputs, widgets, and outputs (they stay grouped by node though)
   3. Select one of the tabs to review/edit either inputs, widgets, or outputs
   4. Rename and toggle visibility of the individual inputs, widgets, and outputs.
![image](https://github.com/user-attachments/assets/d4b617f2-aee2-40cf-ac75-cbf90078a8b2)

**Comment by alessandroperilli** [comment]
I completely forgot about this after one year. Thanks for letting me know, @cbaoth.
It's great to see that now you can rearrange the node orders. Unfortunately, there are still so many little issues with this feature that its huge potential is completely constrained.
