### ISSUE TITLE
Control Net - ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by MarcinSoj** [comfyanonymous/ComfyUI#2310]
Hi everyone. I have problem with control net . It is brand new version : ComfyUI_windows_portable_nvidia_or_cpu_nightly_pytorch.7z from official github repository. I have extracted it and used : update_comfyui_and_python_dependencies.bat. After update it says that everything passed and has been updated. When i start WebUI it shows me this message:

ComfyUI Revision: 1833 [6453dc1c] | Released on '2023-12-16'

Traceback (most recent call last):
  File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.jsonCannot import C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes:
 No module named 'cv2'
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Failed!
Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled.

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI_SimpleMath
   0.0 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.5 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Manager

My config is : .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --lowvram --preview-method auto --disable-cuda-malloc --bf16-vae --fp8_e4m3fn-unet

I tried to copy missing files : opencv_contrib_python-4.8.0.76.dist-info , opencv_python_headless-4.8.0.76.dist-info and opencv_python-4.8.0.76.dist-info but it does not do anything. 

The other thing is also that in site-packages i cannot see files for: controlnet_aux. I can find controlnet_aux and controlnet_aux-0.0.6.dist-info in my Python 3.10 in c:\Python310\Lib\site-packages\. But they are not in : c:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\. 

Maybe there is someone who can investigate this more.

Thank you for help.

**Comment by ltdrdata** [comment]
controlnet aux is not a python package. It's a custom nodes of ComfyUI. And on't install by copying to install python pacakge. Use `.\python_embeded\python.exe -m pip install (package name)`.

**Comment by MarcinSoj** [comment]
Yes thank you. I have researched it more. And it was a problem with 2 extensions : comfyui_controlnet_aux and efficiency-nodes-comfyui. So ModuleNotFoundError: No module named 'cv2' is for comfyui_controlnet_aux and Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled is for efficiency-nodes-comfyui. Hope this will help others with this kind of problems in the future. I will report it to those who take care of those addons. 
Thanks for support.

**Comment by MarcinSoj** [comment]
> controlnet aux is not a python package. It's a custom nodes of ComfyUI. And on't install by copying to install python pacakge. Use `.\python_embeded\python.exe -m pip install (package name)`.

This does not work. When i go to c:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\ and use this command python.exe -m pip install simpleeval
It says: Requirement already satisfied: simpleeval in c:\python310\lib\site-packages (0.9.13)

But it does not install anything into c:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\

Do you have any other ideas ?? thank you.

**Comment by ltdrdata** [comment]
> > controlnet aux is not a python package. It's a custom nodes of ComfyUI. And on't install by copying to install python pacakge. Use `.\python_embeded\python.exe -m pip install (package name)`.
> 
> This does not work. When i go to c:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\ and use this command python.exe -m pip install simpleeval It says: Requirement already satisfied: simpleeval in c:\python310\lib\site-packages (0.9.13)
> 
> But it does not install anything into c:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\
> 
> Same with : opencv-python
> 
> python.exe -m pip install opencv-python Requirement already satisfied: opencv-python in c:\python310\lib\site-packages (4.8.0.76) Requirement already satisfied: numpy>=1.21.2 in c:\python310\lib\site-packages (from opencv-python) (1.24.4)
> 
> Do you have any other ideas ?? thank you.


What command are you using to run ComfyUI?

**Comment by NeedsMoar** [comment]
@MarcinSoj You're trying to install modules into a system python;  python is dumb and will always use the first pip on the system PATH, there's no specific override variable I know of.  If you have a system python in the first place I'd honestly just install comfy as source instead of the executable package and remove around 9000 problems from your setup equations.

@ltdrdata Actually there's a controlnet-aux package on pip (now version 0.0.7 according to pip install --dry-run) but I don't know what installed it on @MarcinSoj's machine.  A large portion of controlnet_aux is CUDA and C++ files so a python module makes more sense than building it every time or outside of the python tree, although I don't have it anywhere so I'm not sure _what_ makes it install itself as a python module.  The pip package isn't in requirements.     

Your manager add-on for Comfy is sadly a better package management system than Python comes with.  I'm getting ready to go through and remove every custom node I've got that has a fixed or <= requirement on a library;  diffusers gets uninstalled and reinstalled like 3 times during an average node update and always ends up on an old version missing chunks of code 3 of the newer nodes use.  Keras keeps getting reverted to broken versions.  This is all because I can't for the life of me find a mechanism to tell pip to freeze a module and it's too stupid to allow for multiple versions at the same time, even though it versions all the installs...   Meanwhile I can go to CPAN from Strawberry Perl on Windows which never worked particularly well because of the huge amounts of GCC related cruft that was historically involved in Perl modules that needed to build anything...  this seems to have become a lot better over the years but until they finally start building Strawberry with MSVC it's not going to be native or work as cleanly.  Activestate now forces you into some bizarro world virtual machine remote configuration environment where you select the modules you want and they're packaged first instead of just providing a basic perl installer so they can go DIAF.   Anyway I'm off topic.    

The worst is that a bunch of the nodes seem to have either their own install.bat which they may or may not just randomly decide to run when updated, or a setup.py that the manager runs when they're updated or installed.  That makes sense since it's what the setup.py is for and I'm fine with it right up until I look at the source and realize all it's doing is readline on the requirements.txt file and shelling out to pip for every requirement in the file...  because the overhead of python setting up a call to a command line utility is roughly around the complexity of the java plugin for mozilla in 1997 trying to launch an applet it takes forever to step through the file this way, then ComfyUI-Manager just runs pip -r requirements.txt like it's supposed to right after and it re-does everything anyway.

**Comment by MarcinSoj** [comment]
> @MarcinSoj You're trying to install modules into a system python; python is dumb and will always use the first pip on the system PATH, there's no specific override variable I know of. If you have a system python in the first place I'd honestly just install comfy as source instead of the executable package and remove around 9000 problems from your setup equations.
> 
> @ltdrdata Actually there's a controlnet-aux package on pip (now version 0.0.7 according to pip install --dry-run) but I don't know what installed it on @MarcinSoj's machine. A large portion of controlnet_aux is CUDA and C++ files so a python module makes more sense than building it every time or outside of the python tree, although I don't have it anywhere so I'm not sure _what_ makes it install itself as a python module. The pip package isn't in requirements.
> 
> Your manager add-on for Comfy is sadly a better package management system than Python comes with. I'm getting ready to go through and remove every custom node I've got that has a fixed or <= requirement on a library; diffusers gets uninstalled and reinstalled like 3 times during an average node update and always ends up on an old version missing chunks of code 3 of the newer nodes use. Keras keeps getting reverted to broken versions. This is all because I can't for the life of me find a mechanism to tell pip to freeze a module and it's too stupid to allow for multiple versions at the same time, even though it versions all the installs... Meanwhile I can go to CPAN from Strawberry Perl on Windows which never worked particularly well because of the huge amounts of GCC related cruft that was historically involved in Perl modules that needed to build anything, pick any random module, and it'll have the whole thing and all deps built and unit tested in a couple minutes without breaking anything despite mingw and hacks like libpthreadswin.dll just begging to break things. this seems to have become a lot better over the years but until they finally start building Strawberry with MSVC it's not going to be native or work as cleanly. Activestate now forces you into some bizarro world virtual machine remote configuration environment where you select the modules you want and they're packaged first instead of just providing a basic perl installer so they can go DIAF. Anyway I'm off topic.
> 
> The worst is that a bunch of the nodes seem to have either their own install.bat which they may or may not just randomly decide to run when updated, or a setup.py that the manager runs when they're updated or installed. That makes sense since it's what the setup.py is for and I'm fine with it right up until I look at the source and realize all it's doing is readline on the requirements.txt file and shelling out to pip for every requirement in the file... because the overhead of python setting up a call to a command line utility is roughly around the complexity of the java plugin for mozilla in 1997 trying to launch an applet it takes forever to step through the file this way, then ComfyUI-Manager just runs pip -r requirements.txt like it's supposed to right after and it re-does everything anyway.

Thank you for all the knowledge. But i think you did not understand my posts. Because there is : "Actually there's a controlnet-aux package on pip" does not mean i want to install it. I am just saying that it is not in : c:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\ folder. That's it i am not expert in Python so i am just giving everything i have done for experts to figure out where is the problem. 
I was trying to install cs2 which ComfyUI wanted because of extension : comfyui_controlnet_aux . Check my post above and you will see that i found out where the problem is. 

p.s : problem is with comfyui_controlnet_aux extension which needs cs2 package. 
Problem solved.
This is for everyone who will have problem with this in the future. Please close this thread not to create unnecessary confusion. 

Thank You.

**Comment by MarcinSoj** [comment]
> > > controlnet aux is not a python package. It's a custom nodes of ComfyUI. And on't install by copying to install python pacakge. Use `.\python_embeded\python.exe -m pip install (package name)`.
> > 
> > 
> > This does not work. When i go to c:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\ and use this command python.exe -m pip install simpleeval It says: Requirement already satisfied: simpleeval in c:\python310\lib\site-packages (0.9.13)
> > But it does not install anything into c:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\
> > Same with : opencv-python
> > python.exe -m pip install opencv-python Requirement already satisfied: opencv-python in c:\python310\lib\site-packages (4.8.0.76) Requirement already satisfied: numpy>=1.21.2 in c:\python310\lib\site-packages (from opencv-python) (1.24.4)
> > Do you have any other ideas ?? thank you.
> 
> What command are you using to run ComfyUI?

I was not using any command to run ComfyUI. Process is simple. You unzip : ComfyUI_windows_portable_nvidia_or_cpu_nightly_pytorch.7z file and run update_comfyui_and_python_dependencies.bat in c:\ComfyUI_windows_portable_nightly_pytorch\update\ and wait to finish. So i did everything as easy and simple as possible :D
Thank you.

**Comment by MarcinSoj** [comment]
Please lock this thread.

**Comment by sfwang78** [comment]
./venv/bin/python -m pip install opencv-python
