### ISSUE TITLE
Does Note Node not support Unicode?

### ISSUE THREAD

**Issue by Hamken100per** [comfyanonymous/ComfyUI#2312]
If you load a workflow entered in Japanese into Note Node from a png, the characters will be garbled.

![notenode_error](https://github.com/comfyanonymous/ComfyUI/assets/2416888/73a10318-47ca-49bf-ac4a-c1f4b7cdadd5)

**Comment by NeedsMoar** [comment]
I tried the regular unicode subrange and the windows shift-JIS compatibility for japanese and there were no problems with either.  
I haven't had the time to learn any of these languages yet...  thanks to how stupid English is I'm in my 40s and still learning my native language.   Apologies if I somehow random-clicked out the foulest insult on the planet to some country or another.

Anyway I installed hte Japanese / Chinese / Korean support fonts after I installed Windows because I hate seeing those squares online, I'd rather see nice characters even if I don't understand them.  Do you have the Japanese language pack installed?
![note](https://github.com/comfyanonymous/ComfyUI/assets/119545088/aeeb97ef-147a-4028-9c03-6e8933d98e2c)

**Comment by Hamken100per** [comment]
Thank you for your reply.
Please forgive me for my poor communication.
The workflow was saved by selecting "Workflow Image->Export->png" from the right-click menu. (Figure below)
Isn't this feature official?

![workflow_export](https://github.com/comfyanonymous/ComfyUI/assets/2416888/3b137173-98ac-4a35-b752-82aaa993c064)

**Comment by NeedsMoar** [comment]
Ah sorry I missed that part.  I tested and it appears to be broken for that node but only when saving workflow images...  workflow image save is from @pythongosssss 's custom nodes.   SVG save just hangs with that text field highlighted so I couldn't check it.  PNGs saved from the animatediff video save node as sidecars to MP4s don't seem to have this issue so it's specific to whatever the workflow image save is doing.

**Comment by Hamken100per** [comment]
Thank you for your reply.
It wasn't an official feature. I'm sorry.
I will report to @pythongosssss.

**Comment by NeedsMoar** [comment]
Looks related to https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/122
