### ISSUE TITLE
Does ComfyUI's SVD discard VideoDecoder's VideoResBlock to reduce VRAM?

### ISSUE THREAD

**Issue by dspmeng** [comfyanonymous/ComfyUI#2348]
The VideoDecoder seems differnt from [official implementation](https://github.com/Stability-AI/generative-models/blob/9d759324e914de6c96dbd1468b3a4a50243c6528/sgm/modules/autoencoding/temporal_ae.py#L293). Does that mean ComfyUI's SVD handle each frame independently in the last VAE decoding stage?

https://github.com/comfyanonymous/ComfyUI/blob/d35267e85a865c30a5fa63fdb0a21f94f4cc37e7/comfy/ldm/modules/temporal_ae.py#L208-L245

**Comment by comfyanonymous** [comment]
It behaves the same I just sometimes refactor things a bit to make the code easier to read for me.

**Comment by dspmeng** [comment]
I see. VideoResBlock is still used under "conv-only" time_mode. Then, where is the magic to achieve such low VRAM? The original VideoDecoder costs nealy 70GB peak VRAM to generate a 25x576x1024 clip.

> It behaves the same I just sometimes refactor things a bit to make the code easier to read for me.

**Comment by NeedsMoar** [comment]
It's probably because it'll tend to be using flash attention / memory efficient from xformers when run in Comfy and I'm guessing they didn't with the original.  Reducing the attention method from quadratic in memory usage with image / batch size growth to below linear works wonders on being able to get things done on normal hardware.  If I turn xformers off some of my workflows with the regular models OOM way sooner than I'd expect them to.  With it turned on I can refine 50 frames of half sized latents upscaled 2x to 1920x1080p in 24GB of vram using animateddiff without splitting the batch up.   

As for why they didn't optimize it...  when people are running on a workstation with 320GB of video ram in 4 H100s and training on an Azure cluster with 25,000 of them because they really need to get the next big thing in "AI" cranked out (and they're not paying the power bill) they don't tend to care...  especially if it's a race to do it before somebody else does or the fad dies down and all the work towards their thesis stops being an automatic degree + hire and it gets reviewed more carefully.  A ton of it is a lot more derivative / incremental than would be accepted in other areas of computer science the way I look at it.  Some of it is really impressive, too, but I'm just saying I don't think the low bar is set very high right now.  :-)

**Comment by dspmeng** [comment]
Besides xformers techniques suggested by @NeedsMoar, diffusers library also includes some SVD low vram tricks：https://huggingface.co/docs/diffusers/using-diffusers/svd#low-memory. Might be helpful for curious guys like me...
