### ISSUE TITLE
[Feature] Expanding ComfyUI to work more like a workspace

### ISSUE THREAD

**Issue by davesierra** [comfyanonymous/ComfyUI#2482]
Greetings. I am trying to feel out the need/want for a feature such as this, and ask for some initial direction.

## Goal:
To make ComfyUI more productive, possibly working a bit more like an IDE such as VSCode. 

Ideally, the first idea is to create "routes" so that the the user can control the session. The routes will load workflow json files. Example, you open a tab `http://127.0.0.1:8188/inpainting-with-controlnet` and this would load `inpainting-with-controlnet.json` in the workflow folder. Now, when the user makes changes (at an interval, on changes, etc) it is automatically (or manually) saved to that json, and no data is lost.

## Background
For as much as I appreciate the work done on ComfyUI coming from a very simple workflow like A1111, I've found ComfyUI's current flow a tad lacking currently when trying to work with intensive productive sessions.

For example, one thing I've noticed is opening many tabs, each with a different workflow.json, sometimes if I refresh in one tab, it will either 1. keep that workflow fairly intact, or 2. load up another workflow.

Another pain point is saving, it always asks to enter a name, hitting Ctrl+S should be a one step thing to save the current session, and it should not deter someone from saving often by repeatedly asking for a filename (easily solved by having a /workflowname).

## Request
How could I go about implementing this? I have experience with web development (specifically js, react, routing, etc) but less so with Python. If something like this were to be implemented, is there a way to keep this separated such as a custom node (in comfy extras perhaps?), so a user could opt into something like this, or would it have to be done into the core of comfy (not ideal but if there's no other options..)? Would you suggest using something like Flask?

# But...
I might be missing something obvious, so if there's a better solution, I'm open. Also, I'm aware that an image keeps the metadata of the workflow, but this doesn't seem always ideal. More often, I do NOT use save image while I'm prototyping a workflow, to save space, not clutter my output folder, etc. Also, if we want to share the image without the metadata, in order to keep our time spent working on the image private.

**Comment by ltdrdata** [comment]
When starting this task, one important aspect to consider is that, by default, workflows are not accessible in ComfyUI until the user uploads them. There needs to be a designated path to store workflows, like `ComfyUI/workflows`, and only the workflows uploaded there should be accessible.

Also, there is an amazing work that allows managing workflows. Take a look at this.
https://github.com/11cafe/comfyui-workspace-manager

**Comment by Weixuanf** [comment]
Hi this is exactly what we are trying to solve with [comfyui-workspace-manager](https://github.com/11cafe/comfyui-workspace-manager)! 

we now have features to let you name and switch between workflows:
<img width="636" alt="Screenshot 2024-01-07 at 7 19 16 PM" src="https://github.com/comfyanonymous/ComfyUI/assets/18367033/464d5507-f4af-495b-ae4d-45f521140dde">
<img width="469" alt="discard changes" src="https://github.com/comfyanonymous/ComfyUI/assets/18367033/9d545c3d-98ed-49b9-8615-7939651baf98">

What you are suggesting aligns with our goals and plans very much!
> Example, you open a tab http://127.0.0.1:8188/inpainting-with-controlnet and this would load inpainting-with-controlnet.json in the workflow folder.
 opening many tabs, each with a different workflow.json

wow I was thinking the exactly the same thing! we were just trying to implement this, multi-tabs support and routings of comfyui

> Another pain point is saving, it always asks to enter a name, hitting Ctrl+S should be a one step thing to save the current session, 

I thought of doing this too! but it requires modifying the existing behavior and scripts of comfyui, so i was hesitant to do so...but it definitely worth exploring.

Since you mentioned you have web development, and we're just trying to find more collaborators, are you open to collaborate with us? ☺️ If you are interested, please email me at weixuanfu01@gmail.com or join our discord channel https://discord.gg/a4NYCqEd and pin me @briefPeach

Thank you! I'm eager to hear more of your thoughts since I feel our thoughts align a lot!

**Comment by Weixuanf** [comment]
> When starting this task, one important aspect to consider is that, by default, workflows are not accessible in ComfyUI until the user uploads them. There needs to be a designated path to store workflows, like `ComfyUI/workflows`, and only the workflows uploaded there should be accessible.
> 
> Also, there is an amazing work that allows managing workflows. Take a look at this. https://github.com/11cafe/comfyui-workspace-manager

Thank you for sharing our repo! @ltdrdata ☺️

**Comment by davesierra** [comment]
@Weixuanf I was not aware of that extension, it looks great and exactly what I needed, I will give it a try and if anything share feedback on your repo. Thanks for sharing.
