### ISSUE TITLE
Port scanning?(Fixed)

### ISSUE THREAD

**Issue by Aenon1** [comfyanonymous/ComfyUI#2599]
For the powers that be, Crystools is opening hundreds+ of time wait connections on local ports every time I open ComfyUI. I disabled it and the issue stopped. This makes ComfyUI look bad. You can install this through manager. https://github.com/crystian/ComfyUI-Crystools

**Comment by ltdrdata** [comment]
ComfyUI never port scan. This is open source software. So, you'd better investigate what is going on your machine by yourself.

**Comment by Aenon1** [comment]
As soon as I close ComfyUI, it stops. I can open the browser without ComfyUI running and it doesn't happen. I'm not digging at ComfyUI, It is my go to app for creating images/video. I just want to know what is happening and how do I stop it.

**Comment by ltdrdata** [comment]
> As soon as I close ComfyUI, it stops. I can open the browser without ComfyUI running and it doesn't happen. I'm not digging at ComfyUI, It is my go to app for creating images/video. I just want to know what is happening and how do I stop it.

I recommend that start from disabling all custom nodes.

**Comment by Aenon1** [comment]
I'll give it a shot. Every node I use is loaded through manager.

**Comment by ltdrdata** [comment]
> I'll give it a shot. Every node I use is loaded through manager.

If you discover that a specific custom node is causing the issue, please report it.

**Comment by Aenon1** [comment]
I will do that. It is making ComfyUI look bad and I do not want to see that happen. Whatever it is starts opening time wait connections on around port 59000(local) and it's gotten up in to the 60,000s when I stopped it.

**Comment by Aenon1** [comment]
Closing this until I find out what is doing it.

**Comment by Aenon1** [comment]
> ComfyUI never do port scan. This is an open source software. So, you'd better investigate what is going on your machine by yourself. And if you come across any issues, please make sure to leave them here.

I found it and updated the original post.

**Comment by ltdrdata** [comment]
ping @crystian

Please provide an explanation for this issue.

**Comment by Aenon1** [comment]
> ping @crystian
> 
> Please provide an explanation for this issue.

I was seeing a non-stop stream of time wait connections being opened. I use TCPView to see my inet connections. This would run as long as I had ComfyUI open and Crystools installed. I am not saying that this was nefarious, but it is a big concern. It appeared that my local ports were being scanned. As soon as I disabled Crystools and restarted ComfyUI, it stopped.

**Comment by crystian** [comment]
Hi people, let me check, please, that behavior is not expected, as @ltdrdata the code is open you can see what it is doing

**Comment by crystian** [comment]
I found the issue is part of [`asyncio.run`](https://github.com/crystian/ComfyUI-Crystools/blob/main/general/monitor.py#L33) 

When it is executed, it makes a new connection (I'm not sure for what); it is not scanning; for some reason, it tries to create a new connection.

It runs by each request info to the hardware to show in the monitor, so, depending on the rate, it will create a new connection.
Let me check how to fix it, but if you have a solution, please let me know!

**Comment by crystian** [comment]
Fixed! Can you test it please? @Aenon1
Update Crystools (1.10.1)

**Comment by crystian** [comment]
Just for documentation:
My configuration:
```
CPU: AMD Ryzen 9 5950X 16-Core Processor - Arch: AMD64 - OS: Windows 10
NVIDIA GeForce RTX 3080 Ti (12 GVRAM)
NVIDIA Driver: 546.33
```

I measure the impact of my extension (because the measure has an impact on time).

Default workflow with 1024x1024 (sd 1.5)
Notes:
* In all cases, I made a simple run to load the model and other stuff, so, in the measure, this is the second time.
* The rate set in monitors is 0.5 (sec)
* "Rate 0" means turn off the loop
* The bath by 20 is via latent batch


### Without my extension:
**x1**: 5.78 segs (3.76 it/s)
**x20**: 99.30 segs (4.57 s/it)

### Previous version:
**x1**
With all monitors on: 5.98 (3.62 it/s)
With all monitors off: 5.81 (3.74 it/s)
Rate 0: 5.87 (3.70 it/s)

**x20**
With all monitors on: 102.41 (4.70 s/it)
With all monitors off: 100.36 (4.61 s/it)
Rate 0: 10.36 (4.63 s/it)

### New version (with the fix):
**x1**
With all monitors on: 5.95 (3.66 it/s)
With all monitors off: 5.88 (3.68 it/s)
Rate 0: 5.93 (3.66 it/s)

**x20**
With all monitors on: 102.64 (4.72 s/it)
With all monitors off: 100.34 (4.62 s/it)
Rate 0: 100.53 (4.63 s/it)

The cost is around: **0.3%**

**Comment by Aenon1** [comment]
> Fixed! Can you test it please? @Aenon1 Update Crystools (1.10.1)
> 
> And thanks for your report!

I reinstalled it and the issue is gone. I updated the post title to reflect that this has been fixed and will close it with this comment. Thank you.

**Comment by formulake** [comment]
> Fixed! Can you test it please? @Aenon1 Update Crystools (1.10.1)
> 
> And thanks for your report!

Amazing reporting and response. Just wanted to drop a note to express how much I appreciate this community.
