### ISSUE TITLE
Refreshing the tab clears the current workflow and loads the default workflow - Solved.

### ISSUE THREAD

**Issue by Aenon1** [comfyanonymous/ComfyUI#2717]
Also, when you use Manager to clear the workflow and do a refresh to reset the blank screen, it loads the default workflow instead of leaving the tab blank.
It has just started doing this. Is there any way to stop it?
I have looked through the settings and I see nothing related. I am using the same nodes that I was using before this began.

**Comment by Aenon1** [comment]
I found out what was causing this, it is comfyui-workspace-manager. I disabled that and all is back to normal.
 (https://github.com/11cafe/comfyui-workspace-manager)

**Comment by pixelpainter** [comment]
I have the same issue and I have never had that custom node installed.. This started happening after a recent update and is very irritating, drag and dropping the last rendered image helps, but there also seems to be a bug where the subgraphs are sometimes not populating the node selections, and they will say Naan,. the only way to usually fix this bug is to refresh the tab, but now I can't do that either. The only work around I have found is to duplicate the subgraph, and the duplicate usually fixes the selection boxes .. but then everything needs to be re-attached.. a pain in the butt sigh......
