### ISSUE TITLE
Group nodes don't use values from converted widgets

### ISSUE THREAD

**Issue by antrobot1234** [comfyanonymous/ComfyUI#2770]
If you take a group node and convert one of it's values to a widget, it will continue to take from the input stored in the group node.
![image](https://github.com/comfyanonymous/ComfyUI/assets/21179158/4c32db26-ed1b-40ab-9a8d-613c71a4d9f0)
![image](https://github.com/comfyanonymous/ComfyUI/assets/21179158/c57c6f3f-9d75-4b2d-a070-a27224de3d67)
I did some digging and it seems that whatever is creating the workflow "prompt" definition is not assigning the input to reference the input node.

**Comment by devingfx** [comment]
+1

**Comment by Lithimlin** [comment]
Any update on this? Like plans to fix it, etc? Been waiting for this fix since February.
For now, I was relying on custom nodes through [palant's Integrated Nodes ](https://github.com/palant/integrated-nodes-comfyui) but that project has been abandoned and I'd much prefer the Group Node option as it allows for easier sharing.

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
