### ISSUE TITLE
Convert image to vector

### ISSUE THREAD

**Issue by YarvixPA** [comfyanonymous/ComfyUI#2797]
I am not a programmer, I am a digital artist and I like to know and experience the tools that add a ComfyUI

I would like to be able to do these. Many times I use websites that have these tool the results in each of them have positive and negative things... without a doubt, in most cases, text vectorization is one of the most difficult, even in other elements. may not be accurate.

Know that this is more like AI for Image, videos and 3D but adding this is like the nodes that we already have to remove background images

**Comment by Woisek** [comment]
You should use tools that are meant for specific tasks. So for vectorizing images, your best bets are Adobe Illustrator or Vector Magic.

**Comment by joelandresnavarro** [comment]
Yes, I know but I wanted to know if an implementation in comfyui was possible so as not to have to resort to pages with those similar functions

I'll keep waiting to see if someone says something... Thanks for your comment

**Comment by imperator-maximus** [comment]
I think there are always a need for good nodes:
- vectorizer 
- good inpainting VAE for SD 1.5 
- better background removal  - the current ones are garbage so far I have tested

For the core project I see only inpainting VAE here as an important. Others would be better in separate projects from other devs.  Coming to vectorizer question: it is on my todo-list but I am not sure if I make ComfyUI node because I am using JS implementation on client and not server side Python at the moment but I am planning to make a better background removal node.
