### ISSUE TITLE
Latest commit seems to completely break CLIP text encode nodes of every kind. basic, sdxl, etc

### ISSUE THREAD

**Issue by ShadwDrgn** [comfyanonymous/ComfyUI#2814]
error log:
https://pastebin.com/YzHGhYSQ
This is the last good commit that works for me:
5b40e7a5ed192e217575c55e061c17a52cf9a15d

**Comment by ShadwDrgn** [comment]
@Th3Rom3  sorry but i don't know what that means. I haven't changed any such setting. I literally just add a ClipTextEncode node and type into it. Where can i change this?

**Comment by Th3Rom3** [comment]
I was referencing a simple workflow using the new Stable Cascade models and pipeline (e.g. [see here](https://gist.github.com/comfyanonymous/0f09119a342d0dd825bb2d99d19b781c))
All other workflows using "normal" Clip Encode seem to be broken for me right now.

Might be a ROCm thing again similar to what was fixed in 6c875d8

**Comment by eliganim** [comment]
> error log: https://pastebin.com/YzHGhYSQ This is the last good commit that works for me: [5b40e7a](https://github.com/comfyanonymous/ComfyUI/commit/5b40e7a5ed192e217575c55e061c17a52cf9a15d)

Same here. Thanks for providing the commit hash that worked for you.

**Comment by Kefka** [comment]
Having similar issues under a directML install.

**Comment by comfyanonymous** [comment]
It's fixed now sorry about that.

**Comment by Th3Rom3** [comment]
Looks like it works again, however the limitations with clip encode as mentioned in #2809 now seem to apply to standard workflows, too. i.e. using parentheses in prompts will throw an error.
