### ISSUE TITLE
Comfy not using all provided threads

### ISSUE THREAD

**Issue by NullEqualsZero** [comfyanonymous/ComfyUI#3121]
I am getting this warning. 
`Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.` 
I am not sure what to do. My GPU is not that great so the more optimizing the better.

**Comment by Ch-Shi** [comment]
I also received this warning and I don't quite understand it. Does this affect performance? Can I increase this value to speed up my workflow? Because I have multiple GPUs running different workflows at the same time.

Here is my configuration:
GPUs: RTX 4090 (24GB) x 2
CPU: 24 vCPUs Intel® Xeon® Platinum 8352V CPU @ 2.10GHz
RAM: 180GB

**Comment by christian-byrne** [comment]
The message is from [this function](https://github.com/pydata/numexpr/blob/b68de57bfed90684b3ea79060c3a7953b9629429/numexpr/utils.py#L119-L164). It refers to CPU cores.

You can set the `NUMEXPR_MAX_THREADS` environment variable to match your CPU core count as suggested in the message.

**Comment by ltdrdata** [comment]
> How to set the NUMEXPR_MAX_THREADS environment variable

If you are using Windows.
https://www.computerhope.com/issues/ch000549.htm
