### ISSUE TITLE
Increased OOM's after update

### ISSUE THREAD

**Issue by MDMAchine** [comfyanonymous/ComfyUI#3294]
So I have a workflow that I have been using for awhile where I got it how I like it. I am using Tiled Diffusion > Supreme sampler from the extra samplers node which has the option for hires-pyramid noise which I like to use with a 1920x1080 image. Everything worked fine with no OOM's up to commit 0a03009.

I updated all my nodes and there were no issues, however after I updated comfyui to d64e217, I would run the same workflow and get OOM's reliably. And even if I changed the noise sampler and reduced resolution to standard SDXL 1024x1024 (or used another "simple" sampler) it would still throw OOMs. Sometimes to the point I would have to restart comfyui and it may work once or twice but again, would just choke up.

I attempted to throw in latent garbage collector and/or VRAM Dubug, but since its at the sampling stage itself, they didn't help.
I installed another side copy of comfy, still same issue. --force-fp16 made it pretty much guarantee a OOM, using xformers or other cross attention made no difference, disable smart memory management, etc.... The only thing that helped was --force-fp32, which actually reduced VRAM usage by a good 5-10% but was painfully slow, a good 2x+ amount of time. 

So for now I am on git checkout 0a03009, and VRAM memory management works as expected, no OOM's. I didn't get a chance to check other commits to see when exactly the change took place, but I figured I'd report it.

Specs:
Windows
Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Total VRAM 8192 MB, total RAM 48735 MB
xformers version: 0.0.25.post1
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync

**Comment by comfyanonymous** [comment]
Can you check if this commit works? https://github.com/comfyanonymous/ComfyUI/commit/744ac944db24795881cf41fc4ea015e5ea07a444

**Comment by MDMAchine** [comment]
After testing the suggested commit 744ac94, I was still experiencing the same OOM issue. To troubleshoot, I rolled back to a snapshot of version 0a03009, including the nodes. Surprisingly, the problem persisted.

I then examined my workflow and noticed I had recently added several math nodes, including converters like 'int to float', to calculate latent sizes and scaling ratios for my upscaling process. When I removed these math nodes and adjusted my workflow to achieve similar outcomes using alternative nodes (closer to my previous workflow), the OOM errors disappeared. VRAM usage during sampling is now about 10% lower.

Importantly, each workflow resulted in the same image and latent dimensions, so the changes did not involve providing the sampler with unusual dimensions. I wasn't initially aware that these math nodes could impact the sampler stage besides changing the size of the latent/image. Restructuring the workflow and removing these nodes resolved the OOM issues and improved performance.

It must be a unique scenario so I'll close this.

**Comment by vanche1212** [comment]
how to fix it？Wait for version iteration？

**Comment by jdc4429** [comment]
I see issues all the time with OOM when running the API...

Works fine 1-3 times and then.. 
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 502.00 MiB. GPU 0 has a total capacity of 23.90 GiB of which 24.88 MiB is free. Of the allocated memory 23.59 GiB is allocated by PyTorch, and 109.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Got an OOM, unloading all loaded models.
Prompt executed in 11.19 seconds

This seems to especially happen with Flux models.. But same issue now with SD3.5 large and Flux models crashing the application or getting OOM errors.  Could you also fix it so that if it does get an OOM while running the API and unloads the models that it runs the prompt again instead of just sitting there.  I run the API for my website and getting an OOM or crashing means the users sit there waiting wondering where their image is.
