### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by SlipperyPete** [comfyanonymous/ComfyUI#340]
On clicking queue in the UI a traceback  appears in my terminal and nothing is queued, I can't seem to make this function at all. I've had a cursory scan of the lines mentioned in the traceback but nothing stands out to me.

This is on Linux with a RX6900XT, sourcing the venv from my a1111 installation that has been working fine.

```
got prompt
Traceback (most recent call last):
  File "/mnt/arbitrary-storage/StableDiffusion/ComfyUI/execution.py", line 182, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "/mnt/arbitrary-storage/StableDiffusion/ComfyUI/execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "/mnt/arbitrary-storage/StableDiffusion/ComfyUI/execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "/mnt/arbitrary-storage/StableDiffusion/ComfyUI/execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "/mnt/arbitrary-storage/StableDiffusion/ComfyUI/execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "/mnt/arbitrary-storage/StableDiffusion/ComfyUI/nodes.py", line 219, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "/mnt/arbitrary-storage/StableDiffusion/ComfyUI/comfy/sd.py", line 851, in load_checkpoint_guess_config
    sd = load_torch_file(ckpt_path)
  File "/mnt/arbitrary-storage/StableDiffusion/ComfyUI/comfy/sd.py", line 16, in load_torch_file
    if ckpt.lower().endswith(".safetensors"):
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by SlipperyPete** [comment]
Yes, and this happens regardless of which one is selected.

Although I've just had a thought, my models are symlinked from where I have them for a1111, and I've recently had issues with other software not properly reading the lengths of symlinks, is it possible that's the cause? I'll test changing the model directory instead.

**Comment by comfyanonymous** [comment]
Symlinks should work but I recommend using the config file instead: https://github.com/comfyanonymous/ComfyUI/blob/master/extra_model_paths.yaml.example

**Comment by jgranie** [comment]
I had the same issue with symlink on macOS, copying the checkpoint from auto1111 to ComfyUI solves it.

**Comment by ultimatejugadee** [comment]
Thanks, the comments pointed me to the right direction. Thanks @jgranie 

**Details –**
1.	I have RTX 2080 Ti (Windows PC), had my A1111 installation **in other drive** and was trying to use tensor models using syslinks. 
2.	I tried the ymal file as well, but that also did not work and the same error kept coming.

**Solution –**
1.	As suggested by jgrani, the files needed to be copied.

**Probable Issue –**
1.	The ymal or syslink solution does not work in case of different drive. This may be due to the way python handles it. Not sure, but it may be the cause here too as seen previously in my few projects, it might be because links on other drive involves colon character and many python libraries creates issue with that.

**Comment by hike2008** [comment]
All the above methods have been tried and are not effective。
