### ISSUE TITLE
Fail to run two requests with the websocket API

### ISSUE THREAD

**Issue by zhuofengli** [comfyanonymous/ComfyUI#3652]
Hi there

When I send two requests to the API through websocket, only the latter one finishes, and the first one doesn't finish. Anyone else having the same issue?

I was following the API example in the code base, here's my code for sending the requests

```
def queue_prompt(prompt):
    p = {"prompt": prompt, "client_id": client_id}
    data = json.dumps(p).encode('utf-8')
    req =  urllib.request.Request("http://{}/prompt".format(server_address), data=data)
    return json.loads(urllib.request.urlopen(req).read())
```

By adding logging in the code I found the first request started executing, but was cut off by the second request.

**Comment by doctorpangloss** [comment]
read more about how to use ComfyUI as a library here: https://github.com/hiddenswitch/ComfyUI?tab=readme-ov-file#using-comfyui-as-an-api--programmatically

**Comment by mcmonkey4eva** [comment]
Comfy API requests return a `prompt_id` value as seen here in the example script https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/websockets_api_example.py#L30
If you're only getting one of the two results, it's likely you're not properly tracking both prompt_ids independently properly

If you need more help with it you'll have to post all your code, or at least the relevant sections you changed rather than just the queue_prompt function from the example script
