### ISSUE TITLE
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension 

### ISSUE THREAD

**Issue by huru0510** [comfyanonymous/ComfyUI#3756]
<img width="857" alt="11111" src="https://github.com/comfyanonymous/ComfyUI/assets/172618541/a0d438b1-3afe-4fae-bf2a-681ae25c3054">
He's frozen here. He's not responding.

**Comment by ltdrdata** [comment]
How many custom nodes were you trying to install at once?
How long did you wait while it was frozen?

Anyway, if you delete the files in the `ComfyUI-Managers/startup-scripts` path, it will skip the initial dependency installation. After that, try fixing the issues one by one via `try fix` button where errors occur.

**Comment by NeedsMoar** [comment]
> <img alt="11111" width="857" src="https://private-user-images.githubusercontent.com/172618541/340239291-a0d438b1-3afe-4fae-bf2a-681ae25c3054.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDIzMjIsIm5iZiI6MTcxODY0MjAyMiwicGF0aCI6Ii8xNzI2MTg1NDEvMzQwMjM5MjkxLWEwZDQzOGIxLTNhZmUtNGZhZS1iZjJhLTY4MWFlMjVjMzA1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxNjMzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWQ2NTE1YTQ5MmQ4YzRiOTE4YTNhZGM5MGE0MjI4OWQ1ZTJjOGE2OGY5NjU1YTJlMTgxNmQ0OGJmNWY2NzU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5TXcDKMTk9AD8025hpE2GH-pkHhlJ3-gvMmazT0yUKU"> He's frozen here. He's not responding.

Probably weird in your native language since you're using a gendered pronoun, but use "It's frozen here.  It's not responding."   English doesn't have gender for pronouns unless talking about a person and doesn't really have gender for verbs at all.   
And for anyone reading I'm strictly bringing up a language semantics / syntax thing, because I know somebody will take it the wrong way if I don't say that.
