### ISSUE TITLE
Every update changes old image seeds. Is there any way to prevent this?

### ISSUE THREAD

**Issue by jnlarson** [comfyanonymous/ComfyUI#3920]
### Your question

Hello,

I update ComfyUI once every two months. After I update it, I expect that my previous image outputs will still look the same, but they often don't. I don't know if it's the sampler that's changed or something else, but the image always looks either a little different or a lot. Same computer, same prompt, same seed, same etc... different image.

Because of this, launching a ComfyUI update fills me dread at the thought that I'm breaking all of my old outputs to stay up to date, and I often copy Comfy into a backup folder before updating. But I can't keep several backup folders to reference if I want to revisit an image I made two months ago or six. It's not practical.

Is there any way to fix? If it's the samplers that are updating, can I back them up and copy them into an updated Comfy to keep them the same? How would I do this? Or if it's something else, how can I fix this?

It's really troubling me. I appreciate the updates and improvements, but risking old images that I worked hard on is a big problem. Thanks for any help.

**Comment by ltdrdata** [comment]
While occasionally results may differ due to bugs, even if ComfyUI itself hasn't changed at all, just a change in a dependency package like PyTorch can alter the results.
To some extent, we need to accept this as a possibility.

https://www.reddit.com/r/StableDiffusion/comments/1f6t09l/different_versions_of_pytorch_produce_different/

Therefore, if the results change due to an update, it's necessary to first verify whether the dependency environment is identical. If the environment is completely the same but the results are still different, please report which commit caused the change.
