### ISSUE TITLE
LatentBatchSeedBehavior seems to change the seed

### ISSUE THREAD

**Issue by Lalimec** [comfyanonymous/ComfyUI#3926]
### Your question

I would like to know if i am using this node correctly. My expectation was to get 4 of the same image by keeping the seed "fixed". This change causes problems in wf's where I use different prompts for each image in a batch, while trying to keep the seed same.

![workflow (65)](https://github.com/comfyanonymous/ComfyUI/assets/65521426/6a3795f8-7ddc-4f91-9e95-f8c0818d1fff)

### Other

I can get the results I want by using a list for conditioning, but thats not a "batch" obviously. 

![workflow (66)](https://github.com/comfyanonymous/ComfyUI/assets/65521426/71a33e0b-bac7-495e-8f87-6ace8a646186)

**Comment by ltdrdata** [comment]
This issue is related to SDE. SDE is designed to incorporate additional random information during the sampling process.

Because the random seed is set when sampling begins, consistency is guaranteed when sampling in list form. However, in the case of batch sampling, since the sampling of all batches occurs simultaneously, it is applied differently to each image in the batch.

To ensure the generation of identical images, it is necessary to avoid SDE or ancestral samplers.
