### ISSUE TITLE
Load Image node leaks colors into transparency with premultiplied alpha images

### ISSUE THREAD

**Issue by bluevisor** [comfyanonymous/ComfyUI#3963]
### Expected Behavior

When loading image files with alpha, transparent areas should be transparent. The built-in preview in the load image node is actually correct.
This is possibly related to these two issues, but not quite:
https://github.com/comfyanonymous/ComfyUI/issues/1515
https://github.com/comfyanonymous/ComfyUI/issues/1162

### Actual Behavior

but when connected to other nodes, colors would leak to transparent areas. see the top preview image node.
![image](https://github.com/comfyanonymous/ComfyUI/assets/1281585/21f449e3-6dbb-4057-92bf-43570ee7c20e)

### Steps to Reproduce

1. load an image with premultiplied alpha channel. (I have attached my test pattern file for your reference)
![test_pattern_2048](https://github.com/comfyanonymous/ComfyUI/assets/1281585/90174d7f-51e3-4592-8a17-537885f1b817)

2. connect it's image output to a preview image node.

### Debug Logs

```powershell
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-07-06 23:45:52.899387
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: C:\StableDiffusion\Data\Packages\ComfyUI\venv\Scripts\python.exe
** ComfyUI Path: C:\StableDiffusion\Data\Packages\ComfyUI
** Log path: C:\StableDiffusion\Data\Packages\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\StableDiffusion\Data\Packages\ComfyUI\custom_nodes\rgthree-comfy
   0.7 seconds: C:\StableDiffusion\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 65462 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers cross attention
.
.
.
torch version---------------------- 2.3.0+cu121
### Loading: ComfyUI-Impact-Pack (V5.18.12)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
[Impact Pack] Wildcards loading done.
Total VRAM 24576 MB, total RAM 65462 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.44.3)
### ComfyUI Revision: 2340 [2dc84d14] | Released on '2024-07-06'
```

### Other

I discovered this bug while writing my own custom node, it would be super helpful if the default load image node could handle alpha correctly. thank you!

**Comment by shawnington** [comment]
Alpha premultiplication is not done by the load image node.

**Comment by shawnington** [comment]
> the bug is not about losing alpha tho, it's about color leaking into transparency. If you compare the preview image node and the built-in preview in load image node, original image doesn't have any yellow or cyan in it. there's also a gap between RGB blocks.

It is a PIL issue if there is indeed color bleed. It is an RGBA image, the RGB channels are loaded and the A channel is split into the mask. What you see is what the RGB channels of the image actually are without any alpha premultiplication. The preview in the node is simply loaded from the image file by the browser, which does do alpha premultiplication. The actual image is loaded with the Pillow library, and no processing is done to the image that could result in any color bleed. 

I personally agree with you in the sense, that it is an atypical expected behavior, and I would favor handling this in a standard way because it is incorrect, but it is expected behavior none the less. Ive fought to try and bring ways of handling images into line with standard practices before, and lost. 

The reality is that too many nodes, both default and custom currently depend on the behavior as it is to change without breaking them. Doing alpha premultiplication in the LoadImage node will break several downstream image processing nodes that take both the alpha and the image and do their own premultiplication, as multiplying alpha twice will result in unexpected results. 

Apply the mask to your image and you will get the behavior you are expecting.

**Comment by bluevisor** [comment]
Thank you very much for the detailed explanation, I know what to do now.

**Comment by bluevisor** [comment]
Expected Behavior

**Comment by ihmily** [comment]
you can use this custom nodes
https://github.com/ihmily/ComfyUI-Light-Tool 


![image](https://github.com/user-attachments/assets/91f473ea-8c36-48a9-aec6-4418a5b712bc)
