### ISSUE TITLE
display broken when enabling the new beta menu

### ISSUE THREAD

**Issue by crystalwizard** [comfyanonymous/ComfyUI#3974]
### Expected Behavior

I expected that the old menu with to be replaced with the new sleek one located across the bottom or top

### Actual Behavior

after clicking the Gear icon to go to settings, and choosing bottom as the location for the new (beta) menu, my screen redrew and while a new - extremely thin- area across the bottom did appear, the grid, my workflow, and everything else that was on the interface vanish to be replaced with a solid gray across the entire browser window. The area at the bottom, which should have been the menu had a number of black rectangular areas that i could click on and that popped up things like save api - but there were no word or labels in them. i clicked on all of them and never got the settings/configuration menu in order to disable the new menu and return to the old. I wound up having to clear my browser's cache and clear local host. after that, when starting comfy, the old menu appeared correctly, and i was able to go into the settings, enable the new one, and have it show up correctly with my workflow still on the screen. The menu area was also not as thin.

i had done a few generations in comfy before this, hadn't restarted it, and the last generation was still on the screen.

### Steps to Reproduce

all i did was enable the menu after generating some images, i don't recall what workflow I was using at the time, i have 1.5, sdxl, and sd3 workflows, it could have been any of the

### Debug Logs

```powershell
i can't give you this, i've rebooted my machine - but there wasn't anything in the logs, i checked them.
I first asked Matt3o for assistance in his discord and he's the one that said to clear cache.
```

**Comment by LearningCreator** [comment]
I experienced the same issue (using Chrome)

**Expected Behavior**
Beta menu to appear with all text and icons visible

**Actual Behavior**
New menu was visible but the only items visible were "ComfyUI," the workflow name field, the Manager button and "Queue." I did note that if I hovered my mouse over where the additional buttons should be, their respective tooltips were visible. The unexpected behavior is shown in the screenshot below:

![Screenshot 2024-07-11 100926](https://github.com/comfyanonymous/ComfyUI/assets/137179948/cde2970d-d763-40e1-b815-20081c340f96)

**Steps to Reproduce**
N/A

Other
To test if it was cookies/cache related, I opened an incognito window and opened the GUI in it. As you can see by the screenshot, the beta menu appeared as it should:

![Screenshot 2024-07-11 101124](https://github.com/comfyanonymous/ComfyUI/assets/137179948/d4a76074-93b4-4e50-a0f8-a1866382bfe3)

**Resolution**
I closed ComfyUI, cleared Chrome's cookies and cache, restarted ComfyUI and the beta menu appeared as it should.
