### ISSUE TITLE
Updating ComfyUI with "update_comfyui.bat" doesn't work

### ISSUE THREAD

**Issue by petrvavrin** [comfyanonymous/ComfyUI#4091]
### Expected Behavior

Update to the latest version

### Actual Behavior

Error message

### Steps to Reproduce

Run "update_comfyui.bat" in C:\AI\Image\ComfyUI_windows_portable\update

### Debug Logs

```powershell
stashing current changes
creating backup branch: backup_branch_2024-07-24_00_10_46
checking out master branch
Traceback (most recent call last):
  File "C:\AI\Image\ComfyUI_windows_portable\update\update.py", line 65, in <module>
    ref = repo.lookup_reference(branch.name)
                                ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
Press any key to continue . . .
```

### Other

Used version: 0.0.2 - ComfyUI_windows_portable_nvidia.7z

**Comment by petrvavrin** [comment]
Fix when running "Update All" in "ComfyUI Manager". Then you can update normally with "update_comfyui.bat"

**Comment by ltdrdata** [comment]
This issue appears to have occurred because you were not on the main branch. 
(If you restored using the snapshot feature, this phenomenon may have occurred as it forcibly adjusted to that version of ComfyUI.)
In the case of ComfyUI-Manager, it has a feature that forcibly readjusts to the main branch even if you're not on it, which is why it was resolved.

**Comment by KedarWolf** [comment]
I downlkoaded ComfyUI from the Git page and even tried downloading the latest build from https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.3.43
