### ISSUE TITLE
Why can't I use my Lora after the update?

### ISSUE THREAD

**Issue by wuyougg** [comfyanonymous/ComfyUI#4308]
Why can't I use my Lora after the update?

**Comment by ltdrdata** [comment]
There is no information in your description of the phenomenon, so we cannot diagnose.

Please provide details on which LoRA model you are using and upload the terminal log (the full log including version information).

**Comment by wuyougg** [comment]
got prompt
Requested to load BaseModel
Loading 1 new model
loaded in lowvram mode 64.0
Requested to load AutoencoderKL
Loading 1 new model
loaded in lowvram mode 64.0


I use tcd sd1.5 Lora

**Comment by ltdrdata** [comment]
The reason I requested the full log was to check your environment and examine any errors that occurred earlier.

**Comment by Kinglord** [comment]
I'm not sure but this person might be seeing the same issue I have been after I tried to update to a new version beyond 0.0.4

I have some more details in this thread because I thought it was a core sampler issue, but it appears to be something with the Lora loaders. - https://github.com/comfyanonymous/ComfyUI/issues/4271#issuecomment-2285055709

Essentially I'm unable to do any batch processing as it appears that using Loras causes the memory to overrun, resulting in very poor performance, lowvram mode kicking in, giving worse performance, and eventually a total crash of comfy and/or the GPU.

Happy to help troubleshoot and provide more details in this thread since it's not related to Flux and is affecting all my SDXL worfkflows that use Loras.

**Comment by BigBanje** [comment]
Suddenly unable to use Loras at all, as well. I was previously able to do --highvram in both fp16 and fp8, with loras and hires fix.

I can't even do fp8 anymore, something has gotten very messed up again. I can't use comfyui at all right now... 3090 with 24GB VRAM + 16GB RAM.

I can literally train a Lora off my computer without issue, yet I can't even use Comfyui to make a creation with it anymore. Something is quite broken with Loras or Lora loaders in there, that's my best guess.

**Comment by comfyanonymous** [comment]
Use the release standalone package on the readme or downgrade pytorch to 2.3.1

**Comment by wuyougg** [comment]
Thanks, I solved the problem by installing a new standalone package
