### ISSUE TITLE
Primitive Node Resets/Collapses to Original Size on Browser Refresh.

### ISSUE THREAD

**Issue by StellarBeing25** [comfyanonymous/ComfyUI#4399]
### Expected Behavior

The primitive node must save and retain its resize data like other nodes in the workflow.

### Actual Behavior

The primitive node always gets reset to its original size, making the widgets unreadable and has to be adjusted every time when opening a saved workflow which is not very user friendly.
![Screenshot](https://github.com/user-attachments/assets/014b6969-8134-4f09-a2f5-08640b6ff46a)

### Steps to Reproduce

Add a primitive node to a workflow, resize it, and then refresh the browser.

### Debug Logs

```powershell
No log for the issue.
```

**Comment by JorgeR81** [comment]
Same for me.
I hope they fix this. 
As a workaround, you can add [ SPACE ] chars to the node title to adjust the size.

**Comment by PrometheusDante** [comment]
Locking the node might help as well, did not test with primitives though. Though locking is user unfriendly as well, when you intend to share the workflow, at least in my book.

**Comment by JorgeR81** [comment]
Strangely, there is no option for locking primitive nodes.
( Maybe a primitive node limitation ? )

![prim](https://github.com/user-attachments/assets/51301cc1-ff62-4547-9d83-4b5e4343e70b)



Also, locking is a custom node feature. 
https://github.com/pythongosssss/ComfyUI-Custom-Scripts?tab=readme-ov-file#lock-nodes--groups

**Comment by PrometheusDante** [comment]
Oh, fair enough. It is hard to keep track of all the mess in the context menu. Gets a bit convoluted after accumulating a few node packs. Could definitely do with some kind of custom setting to toggle on/off all additional entries to get rid of everything one never uses.

That aside, you are right of course, it has no lock option. There are a few other nodes not lockable as well like the default `Note` or `Fast Groups Muter (rgthree)` for example, so that is not a primitive-specific limitation. 

I believe the issue might have to do with nodes going for some sort of default sizing, like the `Preview Image` node insists on a certain minimum height—_unless locked_—which in case of the primitive might be a little extra as it gets its entire functional identity in reference to what it is connected to, potentially resulting in that moment of determining its minimum size happening before it even knows what is or does.

**Comment by mcmonkey4eva** [comment]
frontend issues go @ https://github.com/Comfy-Org/ComfyUI_frontend/

**Comment by JorgeR81** [comment]
Do you mean, issues directly related to the new frontend or any GUI issue ( without a console error ) ?

This is an old issue. I also exists in the old frontend.

**Comment by StellarBeing25** [comment]
@mcmonkey4eva This is not a frontend issue as it is related to how primitive node info is saved in the workflow and is also present in the old UI.

**Comment by mcmonkey4eva** [comment]
This is a frontend issue, Primitive isn't even a core engine feature, backend (API) version of workflows entirely remove Primitive nodes.

**Comment by huchenlei** [comment]
Fixed in https://github.com/Comfy-Org/ComfyUI_frontend/pull/683
