### ISSUE TITLE
search "bypass" find no result

### ISSUE THREAD

**Issue by czcz1024** [comfyanonymous/ComfyUI#4407]
### Your question

in old search type bypass can find rgthree bypass nodes.
in new search and side bar search it find no result

**Comment by huchenlei** [comment]
You can fallback to old searchbox for now.\
![image](https://github.com/user-attachments/assets/80023454-4975-4909-b6dd-4ea6f7413a63)

I think the root issue is that rgthree node is directly calling LiteGraph's register node function instead of calling the register node function on app. I am going to file an issue in the rgthree repo.
