### ISSUE TITLE
Stuck in the search mode after double click

### ISSUE THREAD

**Issue by visaeon** [comfyanonymous/ComfyUI#4438]
### Expected Behavior

Double click brings up a seach bar listing all my nodes

### Actual Behavior

Search bar just constantly loads and nothing happens, no nodes appear

### Steps to Reproduce

Double click to load nodes

### Debug Logs

```powershell
There is no error logged
```

**Comment by visaeon** [comment]
![image](https://github.com/user-attachments/assets/869d5f69-c0ee-48bd-8c90-13ce6805e86a)

**Comment by huchenlei** [comment]
Please file an issue here with full browser log. This is likely due to exception/error when initializing node defs. We need to see full browser log to diagnose it. https://github.com/Comfy-Org/ComfyUI_frontend/issues

Optionally you can try disable custom node to see which one is causing you the issue. You can use comfy-cli's bisect feature if you are having too many of custom nodes enabled. https://github.com/Comfy-Org/comfy-cli#bisect-custom-nodes

**Comment by gonzalu** [comment]
I believe it is the Manager... I have disabled all nodes except the manager and the problem persists. 

Oh well. I'll wait for a fix ....
