### ISSUE TITLE
Loops do not repeat execution for leaf nodes (for Execution Model Inversion)

### ISSUE THREAD

**Issue by Shyryp** [comfyanonymous/ComfyUI#4647]
### Expected Behavior

I would expect that the final branches (leaf nodes (nodes without return pins)) in the loop body would also be re-executed with each loop, or I would expect to be able to control this somehow, but I haven't found such functionality.

### Actual Behavior

Currently, any leaf nodes in the node tree inside the loop body are not executed in subsequent loops (leaf nodes are executed only once). For example, in the screenshot below, you can see that the preview (on the left) of the very first image created by the loop is displayed, rather than the very last image that is displayed after the loop (on the right). While the loop is running, the image previews are not updated inside the loop body.

Screenshot with workflow with problem:
![image](https://github.com/user-attachments/assets/743708a3-24de-456d-bea1-60fe852aa305)

Issue/bug for @guill 

### Steps to Reproduce

Here is a simple workflow that makes it easy to reproduce this issue:
[Leaf_Node_Problem_Example_Workprocess.json](https://github.com/user-attachments/files/16773558/Leaf_Node_Problem_Example_Workprocess.json)

### Debug Logs

```powershell
-
```

### Other

Is it possible to force leaf nodes (nodes without return pins) to be re-executed in Execution Model Inversion? If so, how? Or will this be implemented in the future?

**Comment by Shyryp** [comment]
UPD: Ticket/bug for @guill

**Comment by guill** [comment]
This one actually is feedback for my node pack rather than the core ComfyUI. I implemented my For Loops to exclude leaf nodes, but someone else could do theirs differently without modifying ComfyUI.

It's not technically a bug (it was an intentional implementation decision), but you're definitely not the first to suggest that things should work differently. If you want to move this issue to my execution inversion demo repo, I'll try to get to it at some point.
