### ISSUE TITLE
How to locate a node by its node number?

### ISSUE THREAD

**Issue by K-O-N-B** [comfyanonymous/ComfyUI#4789]
### Your question

btw, how to display number like this?
![image](https://github.com/user-attachments/assets/3a6b497d-77ab-473d-902d-1552387403ca)

:)

**Comment by ltdrdata** [comment]
This would be good to submit as a feature request to the frontend repo.
https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by tampadesignr** [comment]
> This would be good to submit as a feature request to the frontend repo. https://github.com/Comfy-Org/ComfyUI_frontend

this is experienced 20000 times a day lol... how is it not right there when the issue referring to the node in question pops up
this needs to be implemented asap

example 

Cannot execute because a node is missing the class_type property.: Node ID '#1547'

now below it
would be options

1. jump to location
2. which family of nodes its from
3. possible conflicts
4. etc... you know better them me

anyway hope to see this implemented

---------------------------
also you are the og 
could be a spot in control manager drop a number in and it gives above option

anyway.. make life easier i could be creating amazing art...

**Comment by HAL-XP** [comment]
It's available through "Nodes Map  Shift-m" in ComfyUI-EasyUse see : 
https://github.com/Comfy-Org/ComfyUI_frontend/issues/4089#issuecomment-3338704150

**Comment by tampadesignr** [comment]
> It's available through "Nodes Map Shift-m" in ComfyUI-EasyUse see : [Comfy-Org/ComfyUI_frontend#4089 (comment)](https://github.com/Comfy-Org/ComfyUI_frontend/issues/4089#issuecomment-3338704150)

this is something that should be implemented to the ui/ux
can this be pushed to the dev team
https://www.reddit.com/r/comfyui/comments/1pd7xuc/why_is_no_one_talking_about_this_horrible_ux/
since they are listening... cool... now one step closer
