### ISSUE TITLE
How to use the beta TorchCompileModel node?

### ISSUE THREAD

**Issue by pandayummy** [comfyanonymous/ComfyUI#4912]
### Your question

![image](https://github.com/user-attachments/assets/c6c90e68-f62f-4d1b-9ec9-23662f1d4ddc)

Any workflow with it?

**Comment by ltdrdata** [comment]
Just pass the model that goes into KSampler through that node to apply it.
However, when you apply that node, it will take a long time on the first KSampler run, almost as if it's become unresponsive.

**Comment by TripleHeadedMonkey** [comment]
Should be noted that this node requires either Linux, or WSL2 to function.

![image](https://github.com/user-attachments/assets/029727ed-e2ed-477c-83dc-414c5f91c6fd)

And furthermore it does NOT work on anything Pre-RTX.

![image](https://github.com/user-attachments/assets/54af8783-2f18-4914-9191-0705c325fb2c)

I personally will have to reinstall windows entirely, or install LINUX in order to use this node. Sadly I have an issue with my version of windows which does not allow me to update or install certain things.

![image](https://github.com/user-attachments/assets/5448ed9e-7185-4204-9a80-91e8390b4ca7)

![image](https://github.com/user-attachments/assets/fb6768c8-a5a9-475c-a8e0-387d4caa02ce)

![image](https://github.com/user-attachments/assets/b4d5aaee-dfed-423c-8e33-71858300e6c6)

if you could add a PSA for people who might think they're doing something wrong in such cases that might be helpful.

**Comment by ltdrdata** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/d0b7ab88ba0f1cb4ab16e0425f5229e60c934536

**Comment by wtesler** [comment]
It's possible now on Windows using this Triton Windows project: https://github.com/woct0rdho/triton-windows
