### ISSUE TITLE
Tiled Sampler for FLUX

### ISSUE THREAD

**Issue by VladimirNCh** [comfyanonymous/ComfyUI#4955]
### Your question

Is there a node for FLUX that supports TiledSampler? The ones I've tried don't work with UNet models, and this could help generate larger images on weak graphics cards.

I have a Quadro K620 with 2GB of video memory and 16GB RAM and it is not possible to make changes to the configuration of this computer. 

Model: Flux1-schnell. The maximum resolution I manage to generate is 768x1024 or 1024x768. Although the generation is very slow (20 minutes for 5 steps), but it is enough for my needs
![img_00024_](https://github.com/user-attachments/assets/40bc2c14-62ff-410a-8f49-f7cc391ce7fc)

**Comment by Poukpalaova** [comment]
> ### Your question
> Is there a node for FLUX that supports TiledSampler? The ones I've tried don't work with UNet models, and this could help generate larger images on weak graphics cards.
> 
> I have a Quadro K620 with 2GB of video memory and 16GB RAM and it is not possible to make changes to the configuration of this computer.
> 
> Model: Flux1-schnell. The maximum resolution I manage to generate is 768x1024 or 1024x768. Although the generation is very slow (20 minutes for 5 steps), but it is enough for my needs ![img_00024_](https://private-user-images.githubusercontent.com/50941911/368061738-40bc2c14-62ff-410a-8f49-f7cc391ce7fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MjU4MDEsIm5iZiI6MTcyNjYyNTUwMSwicGF0aCI6Ii81MDk0MTkxMS8zNjgwNjE3MzgtNDBiYzJjMTQtNjJmZi00MTBhLThmNDktZjdjYzM5MWNlN2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAyMTE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNTA4MGRmOGE2MDUyMTRhOTE0NmIxYzMyOGFhYjA0ODFlMzFkMzg1Yzg2MzVmYjNhNGUyZDA5YTA2NWJiNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hYn7fryM4htMS_3qB3BSD3gep7MKPGM1BHRnFe_kHs4)
> 
> ### Logs
> _No response_
> 
> ### Other
> _No response_

use those node
![image](https://github.com/user-attachments/assets/9faed26d-48e6-461d-a09e-4853c478ff12)

**Comment by camoody1** [comment]
@Poukpalaova The OP is asking to help on weaker GPUs. I don't think suggesting a 6GB ControlNet model is really the help that he needs.

**Comment by Adreitz** [comment]
Flux doesn't really need a controlnet to do tiled upscaling. You can get very coherent results just using Ultimate SD Upscale node and a low denoise strength of about 0.20. If a particular prompt and seed has visible seams or hallucinations, you can instead use this tiled diffusion node that supports multiple different algorithms: https://github.com/shiimizu/ComfyUI-TiledDiffusion. For me, Mixture of Diffusers with a tile overlap of 64 seems to work pretty well. It is slower than Ultimate SD Upscale, though.

**Comment by VladimirNCh** [comment]
> https://github.com/shiimizu/ComfyUI-TiledDiffusion. For me, Mixture of Diffusers with a tile overlap of 64 seems to work pretty well. It is slower than Ultimate SD Upscale, though.

Thank you. Yes, it allowed to generate images larger than 1024x1024, but they appear with artifacts in the form of repeats of certain areas. Maybe it's in the settings, I will test further.

**Comment by Adreitz** [comment]
Are you taking your initial image, scaling it, doing a VAE Encode, and feeding it back in as your latent image? You need to start with your initial image or the final output will contain only repeats and won't look much like your initial image. The low denoise strength on the tiled stage is also important, so that Flux takes most of its guidance from the initial image.

Note that the VAE Encode and VAE Decode steps are quite memory heavy, so I recommend using VAE Encode (Tiled) and VAE Decode (Tiled) on the second stage with a tile size of 1024 so you don't overwhelm your VRAM. These nodes are now part of core, though they are still in testing. The Tiled Diffusion custom node I linked above also contains its own tiled encode/decode nodes, but for me they seemed to use more memory.

Load this image into comfy if you want to see my workflow, though it is not meant for low VRAM situations. Note that my testing showed that the output quality is affected by the method of upscaling of the initial image. I was most happy with 4x UltraSharp as the upscaling model. This workflow is also a little more complicated than it needs to be so that I can use custom ODE solvers using either https://github.com/redhottensors/ComfyUI-ODE or https://github.com/memmaptensor/ComfyUI-RK-Sampler (the latter is slower for me).
![ComfyUI_00025_](https://github.com/user-attachments/assets/0960c2f5-dd4f-4e18-bc75-6d4f79c4a579)
