### ISSUE TITLE
Batch count become extremly slow in loading "Got prompt"

### ISSUE THREAD

**Issue by CocoPuffLeo** [comfyanonymous/ComfyUI#5073]
### Your question

I use batch count to generate 100 images at a time, using multiple different tabs for different generation before I go to bed. However, after a recent update, I noticed the "got prompt" process has become extremely slow. I rolled back but the problem still persisted. Usually, it should only take seconds for comfyui to load all the prompts, now it can take up to hours. 
I check the command panel and it looks like comfyui is trying to generate the queued image and getting the prompts at the same time, causing these two things to clash against each other. 
Is there a method or setting that is available to allow comfyui to get all the prompts first and then generate the images? 
Maybe clearing the cache can help(I don't know where it is)? Because sometimes it can get prompt very quickly, like seconds, but I have no idea why. I suspect that because I have generated images before and comfyui is not releasing the vram afterwards? 
Or could it be because I have too many loras in my comfyui folder? I have around 1000 lora's in my folder, but I only use 2 for image generation, could it be this?
I am really in a loop and not sure what to do, so any help are welcomed thanks.

**Comment by ltdrdata** [comment]
The "got prompt" message is displayed when a prompt is transmitted from the front end to the backend.
The slowdown you're describing is very broad.

We need to identify which part is slowing down through step-by-step logging.

case1: When the process of serializing and transmitting from front end to backend is slow
case2: When the process of initiating the workflow in the backend is slow
case3: When the execution of specific nodes during workflow execution is slow
case4: When the system itself is slow due to memory swapping

**Comment by fluffydiveX** [comment]
I also had same problem.
I ran into this problem for the first time is around August when the front-end was updated, so I focused on the commits from this period. Therefore, I found commit after 5cfe38f41c7091b0fd954877d9d7427a8b438b1.

In a large workflow I use that is facing the problem, I checked the cProfile to see what happens between the time got prompt is printed and the Queue size is incremented in the terminal. I found two problems in the cProfile result.

1. The number of calls to `INPUT_TYPES()` was increased from once to 200 times

1. [ComfyUI-Lora-Auto-Trigger-Words](https://github.com/idrirap/ComfyUI-Lora-Auto-Trigger-Words) Extension costs large amount of time.

Problem 1 is in [execution.py](https://github.com/comfyanonymous/ComfyUI/blob/ac2f0523cac112a071de43217ecc741d75e74e53/execution.py) changes on commit 5cfe38f41c7091b0fd954877d9d7427a8b438b1.

After commit 5cfe38f41c7091b0fd954877d9d7427a8b438b1, The line 555 of [execution.py](https://github.com/comfyanonymous/ComfyUI/blob/ac2f0523cac112a071de43217ecc741d75e74e53/execution.py) calls `INPUT_TYPES()` in `get_input_info()` on every inputs in `validate_input()` method. 

https://github.com/comfyanonymous/ComfyUI/blob/ac2f0523cac112a071de43217ecc741d75e74e53/execution.py#L554-L555
https://github.com/comfyanonymous/ComfyUI/blob/ac2f0523cac112a071de43217ecc741d75e74e53/comfy_execution/graph.py#L57-L58

In Problem 2, a similar issue already reported in https://github.com/idrirap/ComfyUI-Lora-Auto-Trigger-Words/issues/30

The issue caused by LoraLoaderStackedAdvanced node.
This node associates images with Lora file paths when INPUT_TYPES is called. After 5cfe38f41c7091b0fd954877d9d7427a8b438b1, `INPUT_TYPES()`  is called on every `validation_input()` method. My 500+ Lora images are loaded every validation process which causes a significant slowdown. 

For these reasons, if a workflow has the node that do a lot of processing in INPUT_TYPES() or if there are many nodes, the queuing time is longer.

To solve the problem, I replaced `get_input_info()` method in [execution.py](https://github.com/comfyanonymous/ComfyUI/blob/ac2f0523cac112a071de43217ecc741d75e74e53/execution.py) as shown in https://github.com/fluffydiveX/ComfyUI/commit/1aa778496fd3b8ab6f21f42fc13219b1a99252d8.
The value of `valid_inputs` in [Comfy_execution/graph.py](https://github.com/comfyanonymous/ComfyUI/blob/ac2f0523cac112a071de43217ecc741d75e74e53/comfy_execution/graph.py) is same as The line 540 of [execution.py](https://github.com/comfyanonymous/ComfyUI/blob/ac2f0523cac112a071de43217ecc741d75e74e53/execution.py), I think no need to evaluate `INPUT_TYPES()` in `get_input_info()`. So I added similar method `_get_input_info()` in [execution.py](https://github.com/comfyanonymous/ComfyUI/blob/ac2f0523cac112a071de43217ecc741d75e74e53/execution.py) and it directly passes `class_inputs`.
https://github.com/comfyanonymous/ComfyUI/blob/ac2f0523cac112a071de43217ecc741d75e74e53/execution.py#L540

This fix is worked in my large Image generation workflow and video workflow but I don't know exactly comfyui execution flow and test environment, this change have possibility of causing another issues.

**Comment by Wildboy85** [comment]
thanks fluffydiveX
this work very well for me
before: 40 sec by image, after: 25 sec by image
1080p image on rtx 4080 sd1.5 insight face, 3 mask, 3 faces, euler cfg pp

**Comment by KLL535** [comment]
Same problem.  
The counter gradually slows down. After 300 it starts to increase very slowly. At 1 per sec. Although everything was fine before and the counter instantly increased to at least 1000. I still don't understand how you solved this problem. I don't use ComfyUI-Lora-Auto-Trigger-Words. But I have a large workflow.

**Comment by christian-byrne** [comment]
https://github.com/Comfy-Org/ComfyUI_frontend/issues/2435

You might find it better to use Queue (Instant) mode via the dropdown arrow on the Queue button instead of queueing very large number of prompts at once.

**Comment by KLL535** [comment]
> [Comfy-Org/ComfyUI_frontend#2435](https://github.com/Comfy-Org/ComfyUI_frontend/issues/2435)
> 
> You might find it better to use Queue (Instant) mode via the dropdown arrow on the Queue button instead of queueing very large number of prompts at once.

Honestly, I don't understand the difference. Both `Queue` and `Queue (Instant)` have absolutely identical behavior - slow down.

I tried loading the simplest workflow. It appears if you close all other workflows. On model 1.5. And everything is the same, a gradual slowdown of the counter if you put **1000** in the queue at once. Until 1000 is collected, you have to wait **3 minutes 30 seconds (!)**. That is, it does not depend on the code of custom nodes.
Up to 100, it seems to be collected quickly. From 100 to 300, it slows down significantly. From 300 to 1000, it's **really slow**. And at the same time, generation works, but also slows down. 

Is this the behavior of everyone or is something broken in me?

**Comment by christian-byrne** [comment]
It's not something broken with your setup, but a general issue that is still in the process of being solved. Can you try using Queue (Instant) with the batch count set to 1?

**Comment by KLL535** [comment]
> It's not something broken with your setup (most likely), but a general issue that is still in the process of being solved. Can you try using Queue (Instant) with the batch count set to 1?

Ok, I understand what the difference. It should be called "infinity queue". I will work like this, but it is less familiar, since the function of the square button has disappeared, although in theory it should have been done so that by pressing the square this infinite generation would simply be interrupted.

**Comment by christian-byrne** [comment]
That's a great idea. I added a feature request for it.
