### ISSUE TITLE
[Feature Request] ControlNet 1.1 support

### ISSUE THREAD

**Issue by catboxanon** [comfyanonymous/ComfyUI#526]
Issue for tracking ControlNet 1.1 support. https://github.com/lllyasviel/ControlNet-v1-1-nightly

Some initial notes of implementation from the author: https://github.com/Mikubill/sd-webui-controlnet/issues/736#issuecomment-1507469942

**Comment by comfyanonymous** [comment]
The controlnet 1.1 files have been working since day 1. The model architecture didn't change so I didn't need to do anything to support them.

The only thing that changed as far as I know is some added preprocessors and this new "global_average_pooling: True" in the shuffle controlnet that I need to look at.

**Comment by janekm** [comment]
The "tile" controlnet is particularly powerful, both for upscaling tasks but also for variation workflows. Perfect usecase for comfyui

**Comment by MoonMoon82** [comment]
But how does the controlnet 1.1 inpainting model work?
(control_v11p_sd15_inpaint)

**Comment by comfyanonymous** [comment]
global average pooling is implemented: https://github.com/comfyanonymous/ComfyUI/commit/700491d81a9faf5370a0c54d869e902bbfc839ec
