### ISSUE TITLE
Unnecessarily high FPS in ComfyUI tab seems to cause unnecessary CPU load in Firefox

### ISSUE THREAD

**Issue by Nekotekina** [comfyanonymous/ComfyUI#5261]
### Expected Behavior

Most websites don't seem to generate any noticeable CPU load when nothing happens on the tab.

### Actual Behavior

![image](https://github.com/user-attachments/assets/204db137-f5dd-4728-a0f2-c391524452d2)

### Steps to Reproduce

Just open ComfyUI in Firefox.

### Debug Logs

```powershell
Total VRAM 24154 MB, total RAM 64001 MB
pytorch version: 2.4.1+cu124
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers cross attention
...
[Crystools INFO] Crystools version: 1.13.1
[Crystools INFO] CPU: Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz - Arch: x86_64 - OS: Linux 6.8.0-45-generic
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3090
[Crystools INFO] NVIDIA Driver: 560.35.03
```

### Other

I don't enable HW acceleration in Firefox because it's buggy and increases GPU usage.

**Comment by LukeG89** [comment]
Have you noticed unusual CPU usage through task manager? Or you are just concerned about the high FPS displayed in the canvas info?
I ask because the high FPS you see is just the refresh rate in your display settings.
Instead, if you have noticed real high CPU usage, there might be a custom node that is causing it.

**Comment by Nekotekina** [comment]
As I said, it's a CPU load that I first noticed, something that peaked around 150% by **Firefox process** during the generation when the GUI itself is barely changed. My refresh rate is 144Hz, what shows in the corner also seems jumping up and down but remains pretty high. The only custom node in use was GGUF loader. When I move the canvas, FPS seems to be something around 60.

**Comment by LukeG89** [comment]
There could be another node, probably an extension. Months ago I had similar problem caused by [cg-use-everywhere](https://github.com/chrisgoringe/cg-use-everywhere) (here's the issue that I had https://github.com/chrisgoringe/cg-use-everywhere/issues/146).

If you disable all custom nodes with the `--disable-all-custom-nodes` argument, do you encounter this problem?
If not, you need to investigate which node is causing the high CPU usage.

**Comment by Nekotekina** [comment]
I tried to disable custom nodes, I think it's the same.
![Screenshot from 2024-10-17 02-24-24](https://github.com/user-attachments/assets/497be37a-27d1-4bd1-a8e7-8424912717ee)
The spikes in CPU load correspond to moving the mouse inside ComfyUI tab.

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
