### ISSUE TITLE
Why it convert to old version when open in MaskEditor

### ISSUE THREAD

**Issue by wGitGod** [comfyanonymous/ComfyUI#5277]
### Expected Behavior

open in MaskEditer

### Actual Behavior

it return a old version and a old workflow covering the current page, I don't know why. I restart the comfyui, but not worked.
![image](https://github.com/user-attachments/assets/190beb05-a38d-435c-9128-d60c2da94e6e)

### Steps to Reproduce

just right click-> open in MaskEditor

### Debug Logs

```powershell
nothing printed
```

### Other

I tried Edge and a brower with chrome, all the same

**Comment by wGitGod** [comment]
Update: I deleted the workflow that skiped to, and then it didn't happen again, still don't know why...

**Comment by wGitGod** [comment]
Update: it happened again, skip to a default workflow

**Comment by Willy-Shenn** [comment]
My mask editor opens correctly, but after drawing the mask and saving it, the mask does not display correctly in the Load Image node upon returning to the UI. It looks the same as the original image without any trace of the mask. I’ve encountered this issue before, but when I removed all custom nodes and tested again, the mask drawing and saving functioned properly. Then, I gradually moved the custom nodes back into the folder in batches, and everything worked fine, even with all the custom nodes in place. I found it strange, but since it worked, I didn’t investigate further. However, the issue has returned. I tried the same method of removing all custom nodes and testing again, but this time, the solution did not work.
https://github.com/comfyanonymous/ComfyUI/issues/3986
