### ISSUE TITLE
Cleanup of latent image size picker nodes

### ISSUE THREAD

**Issue by pandayummy** [comfyanonymous/ComfyUI#5361]
### Feature Idea

We have 3 nodes of the same function in the core now, can we have a cleanup?

![image](https://github.com/user-attachments/assets/a84031ab-47d2-4b7c-b1af-f5c803de2679)

**Comment by ltdrdata** [comment]
`EmptySD3LatentImage` can be replaced with `Empty Latent`.
However, strictly speaking, Empty Latent is a 4-channel latent used in SD1/SDXL, while EmptySD3LatentImage is a 16-channel latent, so they cannot be mixed.
It's just that, for user convenience, when using 16-channel models (SD3, FLUX) in KSampler, a function is provided to convert 4 channels to 16 channels, but this only applies to empty latents.

On the other hand, StableCascade_EmptyLatentImage can never be integrated. Stable Cascade uses different types of latents for each stage, and because it has a very heterogeneous structure that requires some form of connection between those latents, it can never be compatible with other models.
