### ISSUE TITLE
Random / branching prompt not working

### ISSUE THREAD

**Issue by photogsy** [comfyanonymous/ComfyUI#5364]
### Expected Behavior

ONE of the random items in the random prompt syntax should be used in the prompt

### Actual Behavior

ALL of the items in the random prompt syntax are used

### Steps to Reproduce

use a prompt such as "abstract paint art featuring the color {green|red|orange}"

### Debug Logs

```powershell
[nothing of use in log]
```

**Comment by ltdrdata** [comment]
The choice feature using`{a|b}` syntax is only allowed in specific widgets, not in all textboxes.

While previously this feature was allowed by default unless explicitly disabled, it was changed through an update long ago to only be allowed when explicitly enabled.

This change was made because the feature often caused issues when incorrectly applied to various custom nodes where it should not have been used.

**Comment by photogsy** [comment]
Everything is up to date and I was using the built in CLIP Text Encode node.

**Comment by LukeG89** [comment]
@photogsy If you make the same node configuration like in my video, what text outputs do you get?

**Comment by ltdrdata** [comment]
> Everything is up to date and I was using the built in CLIP Text Encode node.

If the same issue occurs in a fresh install of ComfyUI, please post it to the front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
