### ISSUE TITLE
When running a queue task, it takes too long and I want to cancel it. But nothing happens when I click cancel. There are other queue tasks waiting in the queue. How can I solve this problem without restarting? How can I solve it using the API?

### ISSUE THREAD

**Issue by Yuan-ManX** [comfyanonymous/ComfyUI#5421]
### Your question

When running a queue task, it takes too long and I want to cancel it. But nothing happens when I click cancel. There are other queue tasks waiting in the queue. How can I solve this problem without restarting? How can I solve it using the API?

**Comment by ltdrdata** [comment]
Is the cancel function not working at all, or is it just slow?

This depends on what is currently being executed.

While other parts can be stopped immediately, once it enters the inference stage, there are fewer points where we can intervene for forced termination, making it difficult to reduce the intervals.

This tendency is especially pronounced when using very slow GPUs.

**Comment by Mescalamba** [comment]
Im not an OP, but I will chime in.

When I cancel SD15/SDXL/PONY it reacts basically instant, despite GPU running at its maximum (100%) load. CPU is obviously just slacking around.

When I try to cancel FLUX, it just doesnt do a thing. In fact FLUX rather often gets hard stuck and ComfyUI needs to killed and rebooted. Funny enough, FLUX has some issue with not running at 100% GPU load that much, it just fluctuates in upper region of 95% or so. CPU is still slacking there too.

I dont have that great GPU, but apart FLUX I can render most stuff basically realtime.

IMHO, I would even say that problem is FLUX, not ComfyUI. Cause I dont have much issues with other models, if any. Altho to be fair I didnt try much apart latest SD3.5 but thats fairly without problems. But when it comes to FLUX, basically everything is a problem.

**Comment by dxnxz** [comment]
same problem here.

**Comment by Mescalamba** [comment]
> same problem here.

Yea thats basically forever problem, cause FLUX or SD3.5 do some sort of soft-lock that cannot be disrupted, until planned events take action. Its sorta noticeable even on SDXL and similar, but its probably easier to interrupt.
