### ISSUE TITLE
UI frozen on new installed ComfyUI

### ISSUE THREAD

**Issue by 954114865** [comfyanonymous/ComfyUI#5425]
### Expected Behavior

Display nodes, nomally use.

### Actual Behavior

Frozen UI, can't see any nodes in most cases, sometimes the link cable is visible but still no nodes. Can't drag or resize canvas, can't add nodes, just frozen. The manager functions and buttons is fine.
![图片](https://github.com/user-attachments/assets/beaa1c69-c200-411c-b268-83dfd69e59ba)

### Steps to Reproduce

Download latest release, install, open it.

### Debug Logs

```powershell
G:\ComfyUI_windows_portable_bak3>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 24576 MB, total RAM 49064 MB
pytorch version: 2.5.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: G:\ComfyUI_windows_portable_bak3\ComfyUI\web
Adding extra search path checkpoints G:\webui_forge_cu121_torch231\webui\models/Stable-diffusion
Adding extra search path configs G:\webui_forge_cu121_torch231\webui\models/Stable-diffusion
Adding extra search path vae G:\webui_forge_cu121_torch231\webui\models/VAE
Adding extra search path loras G:\webui_forge_cu121_torch231\webui\models/Lora
Adding extra search path loras G:\webui_forge_cu121_torch231\webui\models/LyCORIS
Adding extra search path upscale_models G:\webui_forge_cu121_torch231\webui\models/ESRGAN
Adding extra search path upscale_models G:\webui_forge_cu121_torch231\webui\models/RealESRGAN
Adding extra search path upscale_models G:\webui_forge_cu121_torch231\webui\models/SwinIR
Adding extra search path embeddings G:\webui_forge_cu121_torch231\webui\embeddings
Adding extra search path hypernetworks G:\webui_forge_cu121_torch231\webui\models/hypernetworks
Adding extra search path controlnet G:\webui_forge_cu121_torch231\webui\models/ControlNet
G:\ComfyUI_windows_portable_bak3\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

Import times for custom nodes:
   0.0 seconds: G:\ComfyUI_windows_portable_bak3\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Other

I tryed firefox and edge browser, reboot my computer, not help. 
my other relative UI like forgeUI and Onetrainer is working fine, so it can't be error about python.

**Comment by 954114865** [comment]
![图片](https://github.com/user-attachments/assets/422d408b-7b5e-49a5-82c3-ed7e8779282a)
That's what I say 'sometimes the link cable is visible but still no nodes'

**Comment by LukeG89** [comment]
Have you tried updating ComfyUI through `update_comfyui_stable.bat`?

**Comment by GegenDenTag** [comment]
> Can't drag or resize canvas, can't add nodes, just frozen. The manager functions and buttons is fine.

**Edge + Chrome**
I have a similar issue, maybe since Monday or Tuesday. It can be somewhat resolved by pressing the F5 key, as shown in the mp4 file. Sometimes it requires multiple refreshes or a restart of ComfyUI.

https://github.com/user-attachments/assets/522b2279-8827-4be6-930d-826fa65807ff

**Console**
G:\KI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build

## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-31 02:24:40.842490
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: G:\KI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: G:\KI\ComfyUI_windows_portable\ComfyUI
** Log path: G:\KI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   4.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24575 MB, total RAM 32693 MB
pytorch version: 2.4.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: G:\KI\ComfyUI_windows_portable\ComfyUI\web
Adding extra search path checkpoints G:\KI\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs G:\KI\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae G:\KI\stable-diffusion-webui\models/VAE
Adding extra search path loras G:\KI\stable-diffusion-webui\models/Lora
Adding extra search path loras G:\KI\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models G:\KI\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models G:\KI\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models G:\KI\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings G:\KI\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks G:\KI\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet G:\KI\stable-diffusion-webui\models/ControlNet
G:\KI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
[Crystools INFO] Crystools version: 1.20.0
[Crystools INFO] CPU: AMD Ryzen 9 5900X 12-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3090
[Crystools INFO] NVIDIA Driver: 566.03
G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Disco-Diffusion\guided-diffusion\guided_diffusion\nn.py:143: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @th.cuda.amp.custom_fwd

Import times for custom nodes:
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-padding
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-text-overlay
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BRIA_AI-RMBG
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TextOverlay
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfy_Felsirnodes
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\steerable-motion
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.1 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Dave_CustomNode
   0.1 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.2 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ComfyWorkflows
   0.2 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.3 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.4 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_milehighstyler
   0.8 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.5 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Transparent-Background
   1.8 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   2.5 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Disco-Diffusion
   4.0 seconds: G:\KI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by ltdrdata** [comment]
> ![图片](https://private-user-images.githubusercontent.com/121415253/381561853-422d408b-7b5e-49a5-82c3-ed7e8779282a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDk1OTEsIm5iZiI6MTczMDM0OTI5MSwicGF0aCI6Ii8xMjE0MTUyNTMvMzgxNTYxODUzLTQyMmQ0MDhiLTdiNWUtNDlhNS04MmMzLWVkN2U4Nzc5MjgyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwNDM0NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWRmNjdkYTU0NzJlNTdmMzljNzA0OTFkZTU4M2I2NDZjM2JhYTJkMmI1ODE0NmM3ZWVhMjlmNTU4Y2I1YmJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2WvDCLV5Vhfi_WywwZ542kgCIkVzSq2z2Rd8SDs2_Ic) That's what I say 'sometimes the link cable is visible but still no nodes'

Most users who have been experiencing this issue recently are using an outdated version of mixlab.
Update or remove the mixlab custom node.

**Comment by 954114865** [comment]
> > ![图片](https://private-user-images.githubusercontent.com/121415253/381561853-422d408b-7b5e-49a5-82c3-ed7e8779282a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDk1OTEsIm5iZiI6MTczMDM0OTI5MSwicGF0aCI6Ii8xMjE0MTUyNTMvMzgxNTYxODUzLTQyMmQ0MDhiLTdiNWUtNDlhNS04MmMzLWVkN2U4Nzc5MjgyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwNDM0NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWRmNjdkYTU0NzJlNTdmMzljNzA0OTFkZTU4M2I2NDZjM2JhYTJkMmI1ODE0NmM3ZWVhMjlmNTU4Y2I1YmJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2WvDCLV5Vhfi_WywwZ542kgCIkVzSq2z2Rd8SDs2_Ic) That's what I say 'sometimes the link cable is visible but still no nodes'
> 
> Most users who have been experiencing this issue recently are using an outdated version of mixlab. Update or remove the mixlab custom node.

No this is a fresh install, there are no any custome nodes installed yet.

**Comment by 954114865** [comment]
I found a way solve this, at least for this moment: To change UI's color palette.
That was awful, why could this happen?

**Comment by wazya123** [comment]
最新版本重新安装会出现这个问题，但升级到最新版本不会，搞不懂怎么回事

**Comment by GegenDenTag** [comment]
It's working again for me, it was the nodes from Davemane42 (not Mixlab) in the path
..\ComfyUI_windows_portable\ComfyUI\web\extensions
<img width="413" alt="Screenshot 2024-11-02 204301" src="https://github.com/user-attachments/assets/cbf6896e-8f15-49b3-9369-e6a6285d5466">

The access to app.js is not working. 
Aus DevTools eingefügt
MultiLatentComposite.js:240 Uncaught ReferenceError: graph is not defined
at app.canvas.onDrawBackground (MultiLatentComposite.js:240:4)
at Proxy.drawBackCanvas (litegraph.es.js:5664:12)
at Proxy.draw (litegraph.es.js:5173:12)
at _bg_img.onload (colorPalette.ts:495:14)*

The error is only thrown when using the old version. Over the weekend, I reverted run_nvidia_gpu.bat back to the old Windows stand-alone build (no idea why anymore...).

@954114865 This might not help you with your reinstallation, but it could assist someone else. I think it has something to do with the upgrade, maybe.

**Comment by ltdrdata** [comment]
> It's working again for me, it was the nodes from Davemane42 (not Mixlab) in the path ..\ComfyUI_windows_portable\ComfyUI\web\extensions <img alt="Screenshot 2024-11-02 204301" width="413" src="https://private-user-images.githubusercontent.com/186859960/382473752-cbf6896e-8f15-49b3-9369-e6a6285d5466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NjkwMDYsIm5iZiI6MTczMDU2ODcwNiwicGF0aCI6Ii8xODY4NTk5NjAvMzgyNDczNzUyLWNiZjY4OTZlLThmMTUtNDliMy05MzY5LWU2YTYyODVkNTQ2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxNzMxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDg1ZmRiMjkzOGI2N2YxNTFiYTllOGNmNTdmMTQ3MDY4MTI4OWRmOWQ0Y2IyZGJkMjlhYTJiYTA3MjBkNzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MKxZNbhrCugt4A7_dgexnP3vdrqCCorkA-CrtlVSzhI">
> 
> The access to app.js is not working. Aus DevTools eingefügt MultiLatentComposite.js:240 Uncaught ReferenceError: graph is not defined at app.canvas.onDrawBackground (MultiLatentComposite.js:240:4) at Proxy.drawBackCanvas (litegraph.es.js:5664:12) at Proxy.draw (litegraph.es.js:5173:12) at _bg_img.onload (colorPalette.ts:495:14)*
> 
> The error is only thrown when using the old version. Over the weekend, I reverted run_nvidia_gpu.bat back to the old Windows stand-alone build (no idea why anymore...).
> 
> @954114865 This might not help you with your reinstallation, but it could assist someone else. I think it has something to do with the upgrade, maybe.

That's a very old node that is no longer supported, and because it's a front-end extension that was created a very long time ago, it won't be removed until the user manually deletes it from web/extensions.
Remove ComfyUI_Dave_CustomNode from both custom_nodes and delete it from web/extensions as well.
