### ISSUE TITLE
The worlkflows aren't being loaded now that I UPDATED. I just drag and drop but all I get is the name of the JSON on the left bar. NO WORKFLOW LOADED.

### ISSUE THREAD

**Issue by agustincaniglia** [comfyanonymous/ComfyUI#5704]
### Your question

How can I get my workflow loaded in new updated comfyUI?
![WhatsApp Image 2024-11-21 at 17 54 30](https://github.com/user-attachments/assets/1e6e7782-4ebf-4619-811d-571cedec18d6)

**Comment by LukeG89** [comment]
Try upgrading ComfyUI and all custom nodes.

If this doesn't solve, you could try disabling your custom nodes with the `--disable-all-custom-nodes` argument and see if  the problem is caused by a conflict with one of your nodes.
For example, another user just had a problem with this one: [ComfyUI-tbox](https://github.com/ai-shizuka/ComfyUI-tbox)
