### ISSUE TITLE
Flux redux output not follow the reference image

### ISSUE THREAD

**Issue by frankyifei** [comfyanonymous/ComfyUI#5717]
### Expected Behavior

The reference image seems to be cropped when loaded with the example workflow. First image is the workflow, I use the image itself as reference. The second is the output.
![flux_redux_model_example](https://github.com/user-attachments/assets/17cbbd59-1d6d-47b0-811f-1867990f5492)
![ComfyUI_00489_](https://github.com/user-attachments/assets/caae4ee9-b6bc-4bc3-b717-ef51fb773aac)

### Actual Behavior

The reference image is cropped somehow in the example workfow, resulted in a smaller output. 

### Steps to Reproduce

just load the example redux wordflow with any image

**Comment by currenttime** [comment]
Where is the example workfow?

**Comment by bertguan96** [comment]
Same question, where is the example workflow.

**Comment by currenttime** [comment]
> Same question, where is the example workflow.

I got it!

https://comfyanonymous.github.io/ComfyUI_examples/flux/

**Comment by Samuraizero** [comment]
I have noticed the very same thing. I was at some point so worried it was because I had a badly trained LoRA I redid the training. Twice. Then it hit me to try without LoRA but the same "zoom/crop" kept happening. It also does not happen always on the same level of cropping/zooming, sometimes it is barely noticeable, sometimes is quite bigger. I have resorted to using outpainting first to grow the image so the zoom does not hit the same.

**Comment by frankyifei** [comment]
I fixed it by resize the reference image to 1024×1024, and set the latent
size to original size, it actually fixed the problem

Samuraizero ***@***.***> 于 2024年12月2日周一 08:51写道：

**Comment by comfyanonymous** [comment]
The clip vision encode node now has an option to not crop the image.

**Comment by Samuraizero** [comment]
> The clip vision encode node now has an option to not crop the image.

Noticeably better, thanks. Don't know why but it was not showing that option until I reloaded the official example.
