### ISSUE TITLE
batch images

### ISSUE THREAD

**Issue by Chengym2023** [comfyanonymous/ComfyUI#5744]
### Your question

![image](https://github.com/user-attachments/assets/fe35f218-583b-41ab-8962-d37d429041f3)
how can i get 10 images for this node? in queue i set 10,but it pause at this node. in latent batch size i set 10,but flux can not run

**Comment by ltdrdata** [comment]
It might not be easy to run Flux with a batch size of 10 because of the required resource.

You can create a batch of 10 and use the 'Rebatch Latents' node to split the latents into 10 parts and process them one by one.

If the 'Image Chooser' node can handle a list, no further action is needed. However, if it requires batch input, you can use the 'Rebatch Images' node to split the processed results again and then combine them into a single batch for processing

![image](https://github.com/user-attachments/assets/e79403d2-3b57-4ecc-88ea-ef7ade8d85e6)
