### ISSUE TITLE
Desktop Queue control per tab

### ISSUE THREAD

**Issue by michaelLochlann** [comfyanonymous/ComfyUI#5776]
### Feature Idea

in browser, each tab has its own queue option. Particularly, you can turn auto queue on and off for each tab individually.  This is handy while developing them and testing different things.

On the desktop, the queue/auto queue control works the same for all open tabs, meaning you can no longer do the above control.

While I'd much prefer to be on the desktop this may keep me from migrating to it for now.

**Comment by huchenlei** [comment]
Can you move this issue to https://github.com/Comfy-Org/ComfyUI_frontend/issues ?

**Comment by Silanda** [comment]
I think this could apply to the new UI for browsers too, not just the stand alone app. 

I use 3-4 workflows. One to generate batches of images, one to outpaint, one to upscale, and one to inpaint. 

Using the old UI, each browser tab has its own queue size. With the new UI, using only one tab allows switching between workflows, copying using clipspace, etc, but the queue size is shared between all workflows. It becomes really quite annoying when, for example, I go from outpainting, where I usually have a queue size of 10, to upscaling, and then I wonder why it's taking so long to complete, and it's because I forgot to change the queue back to 1. 

It's not a deal breaker for the new UI for me, but it would seem more efficient if each workflow had its own queue size.
