### ISSUE TITLE
Snaphot Manager - Failed to extract snapshots for custom nodes when "saving snapshot"

### ISSUE THREAD

**Issue by tedtninety** [comfyanonymous/ComfyUI#5986]
### Expected Behavior

Output verifies snapshot saved via CMD  as well as ther GUI.

### Actual Behavior

GUI states "Current snapshot saved" but in the CMD it states multiple failures to extract snapshots for custom nodes:
FETCH DATA from: D:\ComfyUI_windows_portable - Beta\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[]
[]
Failed to extract snapshots for the custom node 'ComfyUI-Advanced-ControlNet'.
Failed to extract snapshots for the custom node 'ComfyUI-AdvancedLivePortrait'.
Failed to extract snapshots for the custom node 'ComfyUI-Custom-Scripts'.
Failed to extract snapshots for the custom node 'ComfyUI-Florence2'.
Failed to extract snapshots for the custom node 'ComfyUI-GGUF'.
Failed to extract snapshots for the custom node 'ComfyUI-Inpaint-CropAndStitch'.
Failed to extract snapshots for the custom node 'ComfyUI-KJNodes'.
Failed to extract snapshots for the custom node 'ComfyUI-layerdiffuse'.
Failed to extract snapshots for the custom node 'ComfyUI-Manager'.
Failed to extract snapshots for the custom node 'ComfyUI-PuLID-Flux'.
Failed to extract snapshots for the custom node 'ComfyUI-PuLID-Flux-Enhanced'.
Failed to extract snapshots for the custom node 'comfyui-tensorops'.
Failed to extract snapshots for the custom node 'ComfyUI-Universal-Styler'.
Failed to extract snapshots for the custom node 'ComfyUI-VideoHelperSuite'.
Failed to extract snapshots for the custom node 'comfyui_controlnet_aux'.
Failed to extract snapshots for the custom node 'ComfyUI_essentials'.
Failed to extract snapshots for the custom node 'ComfyUI_FaceAnalysis'.
Failed to extract snapshots for the custom node 'ComfyUI_InstantID'.
Failed to extract snapshots for the custom node 'ComfyUI_IPAdapter_plus'.
Failed to extract snapshots for the custom node 'comfyui_segment_anything'.
Failed to extract snapshots for the custom node 'Derfuu_ComfyUI_ModdedNodes'.
Failed to extract snapshots for the custom node 'PuLID_ComfyUI'.
Failed to extract snapshots for the custom node 'rgthree-comfy'.
Failed to extract snapshots for the custom node 'x-flux-comfyui'.
Failed to extract snapshots for the custom node 'ComfyUI_AdvancedRefluxControl'.
Failed to extract snapshots for the custom node 'cg-use-everywhere'.
Failed to extract snapshots for the custom node 'comfyui-inpaint-nodes'.
Failed to extract snapshots for the custom node 'Comfyui-In-Context-Lora-Utils'.
Failed to extract snapshots for the custom node 'ComfyUI-Crystools'.

### Steps to Reproduce

Go to Comfy Manager Menu > Click on Snapshot Manager > Save Snapshot

### Debug Logs

```powershell
FETCH DATA from: D:\ComfyUI_windows_portable - Beta\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[]
[]
Failed to extract snapshots for the custom node 'ComfyUI-Advanced-ControlNet'.
Failed to extract snapshots for the custom node 'ComfyUI-AdvancedLivePortrait'.
Failed to extract snapshots for the custom node 'ComfyUI-Custom-Scripts'.
Failed to extract snapshots for the custom node 'ComfyUI-Florence2'.
Failed to extract snapshots for the custom node 'ComfyUI-GGUF'.
Failed to extract snapshots for the custom node 'ComfyUI-Inpaint-CropAndStitch'.
Failed to extract snapshots for the custom node 'ComfyUI-KJNodes'.
Failed to extract snapshots for the custom node 'ComfyUI-layerdiffuse'.
Failed to extract snapshots for the custom node 'ComfyUI-Manager'.
Failed to extract snapshots for the custom node 'ComfyUI-PuLID-Flux'.
Failed to extract snapshots for the custom node 'ComfyUI-PuLID-Flux-Enhanced'.
Failed to extract snapshots for the custom node 'comfyui-tensorops'.
Failed to extract snapshots for the custom node 'ComfyUI-Universal-Styler'.
Failed to extract snapshots for the custom node 'ComfyUI-VideoHelperSuite'.
Failed to extract snapshots for the custom node 'comfyui_controlnet_aux'.
Failed to extract snapshots for the custom node 'ComfyUI_essentials'.
Failed to extract snapshots for the custom node 'ComfyUI_FaceAnalysis'.
Failed to extract snapshots for the custom node 'ComfyUI_InstantID'.
Failed to extract snapshots for the custom node 'ComfyUI_IPAdapter_plus'.
Failed to extract snapshots for the custom node 'comfyui_segment_anything'.
Failed to extract snapshots for the custom node 'Derfuu_ComfyUI_ModdedNodes'.
Failed to extract snapshots for the custom node 'PuLID_ComfyUI'.
Failed to extract snapshots for the custom node 'rgthree-comfy'.
Failed to extract snapshots for the custom node 'x-flux-comfyui'.
Failed to extract snapshots for the custom node 'ComfyUI_AdvancedRefluxControl'.
Failed to extract snapshots for the custom node 'cg-use-everywhere'.
Failed to extract snapshots for the custom node 'comfyui-inpaint-nodes'.
Failed to extract snapshots for the custom node 'Comfyui-In-Context-Lora-Utils'.
Failed to extract snapshots for the custom node 'ComfyUI-Crystools'.
```

**Comment by dreamhacking** [comment]
I am having same problem :(


Update ComfyUI
Cmd('git') failed due to: exit code(1)
  cmdline: git stash
  stderr: 'error: 'models/style_models/put_t2i_style_model_here' is beyond a symbolic link
fatal: Unable to process path models/style_models/put_t2i_style_model_here
Cannot save the current worktree state'
Install: pip packages
Line is comment...skipping
Failed to extract snapshots for the custom node 'attention-couple-ComfyUI'.
Failed to extract snapshots for the custom node 'cg-image-picker.disabled'.
Failed to extract snapshots for the custom node 'cg-use-everywhere'.
Failed to extract snapshots for the custom node 'comfy-image-saver'.
Failed to extract snapshots for the custom node 'comfy-plasma'.
Failed to extract snapshots for the custom node 'ComfyLiterals'.
Failed to extract snapshots for the custom node 'ComfyMath'.
Failed to extract snapshots for the custom node 'ComfyUI-Advanced-ControlNet'.
Failed to extract snapshots for the custom node 'ComfyUI-Allor.disabled'.
Failed to extract snapshots for the custom node 'comfyui-animatediff'.
Failed to extract snapshots for the custom node 'ComfyUI-AnimateDiff-Evolved'.
Failed to extract snapshots for the custom node 'comfyui-art-venture'.
Failed to extract snapshots for the custom node 'ComfyUI-BrushNet'.
Failed to extract snapshots for the custom node 'ComfyUI-Chibi-Nodes.disabled'.
Failed to extract snapshots for the custom node 'ComfyUI-Custom-Scripts'.
Failed to extract snapshots for the custom node 'ComfyUI-Eagle-PNGInfo'.
Failed to extract snapshots for the custom node 'ComfyUI-Easy-Use'.
Failed to extract snapshots for the custom node 'Comfyui-ergouzi-Nodes.disabled'.
Failed to extract snapshots for the custom node 'ComfyUI-Florence2'.
Failed to extract snapshots for the custom node 'ComfyUI-Gemini'.
Failed to extract snapshots for the custom node 'ComfyUI-GGUF'.
Failed to extract snapshots for the custom node 'ComfyUI-GlifNodes'.
Failed to extract snapshots for the custom node 'ComfyUI-IC-Light-Native'.
Failed to extract snapshots for the custom node 'ComfyUI-Image-Filters'.
Failed to extract snapshots for the custom node 'ComfyUI-Impact-Pack'.
Failed to extract snapshots for the custom node 'comfyui-inpaint-nodes'.
Failed to extract snapshots for the custom node 'ComfyUI-Inspire-Pack'.
Failed to extract snapshots for the custom node 'ComfyUI-LaMA-Preprocessor'.
Failed to extract snapshots for the custom node 'comfyui-lama-remover'.
Failed to extract snapshots for the custom node 'ComfyUI-layerdiffuse'.
Failed to extract snapshots for the custom node 'ComfyUI-LivePortraitKJ'.
Failed to extract snapshots for the custom node 'ComfyUI-Logic'.
Failed to extract snapshots for the custom node 'comfyui-magic-clothing'.
Failed to extract snapshots for the custom node 'ComfyUI-Manager'.
Failed to extract snapshots for the custom node 'ComfyUI-MimicMotionWrapper'.

**Comment by tedtninety** [comment]
> I am having same problem :(

It's a shame because it is such a good feature to have especially when installing custom nodes that need a litany of requirements that can clash existing versions.

**Comment by LukeG89** [comment]
@tedtninety You need to open a bug report in [ComfyUI-Manager](https://github.com/ltdrdata/ComfyUI-Manager) repo

**Comment by tedtninety** [comment]
> @tedtninety You need to open a bug report in [ComfyUI-Manager](https://github.com/ltdrdata/ComfyUI-Manager) repo

You're absolutely correct. Thank you.
For others with the same issue:
https://github.com/ltdrdata/ComfyUI-Manager/issues/1331

**Comment by tedtninety** [comment]
Moved over to Comfy UI Manager.
