### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Vidazare** [comfyanonymous/ComfyUI#6186]
### Your question

[Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts\\LiheYoung\\Depth-Anything\\.cache\\huggingface\\download\\checkpoints\\depth_anything_vitl14.pth.6c6a383e33e51c5fdfbf31e7ebcda943973a9e6a1cbef1564afe58d7f2e8fe63.incomplete' is:issue 

### Logs

```powershell
.
```

**Comment by LukeG89** [comment]
It's a known issue:
- https://github.com/Fannovel16/comfyui_controlnet_aux/issues/264

The problem is caused by your ComfyUI path, reduce it to `D:\ComfyUI_windows_portable\ComfyUI` and try again.
If the problem still persists, I suggest deleting the `.cache` folder in `ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\LiheYoung\Depth-Anything`

**Comment by LukeG89** [comment]
Anyways, I would suggest Depth Anything V2

![image](https://github.com/user-attachments/assets/08a1710c-faf4-45f7-86c6-7911432ecd39)
