### ISSUE TITLE
How to interrupt operation?

### ISSUE THREAD

**Issue by daizhuo** [comfyanonymous/ComfyUI#708]
Hi......
I don't know how to How to interrupt operation.
Is there a buttom to do that when you find something go wrong during the progressing.
Thank you!

PS： I’m not a programmer T_T

**Comment by comfyanonymous** [comment]
See Queue -> Running -> Cancel

**Comment by daizhuo** [comment]
> See Queue -> Running -> Cancel

**Comment by daizhuo** [comment]
Wow.....
Thanks a lot for your quick answer.
BTW, how' going with the Mask Painting node?
Really need that in inpaint.
It's better would have inpaint sketch too, something like you can draw a color bus in WebUI I2I.
Thank you so much!

**Comment by comfyanonymous** [comment]
You can right click the "Load Image" node and -> open in MaskEditor

**Comment by ltdrdata** [comment]
> Wow..... Thanks a lot for your quick answer. BTW, how' going with the Mask Painting node? Really need that in inpaint. It's better would have inpaint sketch too, something like you can draw a color bus in WebUI I2I. Thank you so much!

Alternatively, you can copy to clipspace from any image node using **Copy (clipspace)**, edit it in the mask editor under Clipspace in the main menu, and then paste it to the desired node using **Paste (clipspace)**. This can be utilized similar to the **send to ...** feature of img2img.

Additionally, if you install the ComfyUI-Impact-Pack extension, you can use the ```PreviewBridge``` node to edit masks at intermediate points in the workflow instead of just the starting point.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/previewbridge.md

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/sam_with_preview_bridge.md
