### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by bigbaldy1128** [comfyanonymous/ComfyUI#933]
I requested the API according to https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/websockets_api_example.py, but I received HTTP Error 400: Bad Request, how can I address this issue?

**Comment by Adenialzz** [comment]
same

**Comment by Adenialzz** [comment]
have you solved this?

**Comment by dreamshit** [comment]
I had the same trouble，check your checkpoints name in the prompt

**Comment by araleza** [comment]
Can confirm what dream said. The default model file in the example code is:
```
"ckpt_name": "v1-5-pruned-emaonly.ckpt"
```
but you might not have the -emaonly version, and models tend to be .safetensors instead of .ckpt now. As an example, I changed this line to load `v1-5-pruned.safetensors`, and that got rid of the vague '400: Bad Request' error for me.

**Comment by ltdrdata** [comment]
This issue will be closed. If the problem is not resolved using the method provided in the answer, please create a separate issue with more specific details.
